### ISSUE TITLE
new module: core

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#1]
- `fontstyle` functions for (enforcing sizing and weights for various font outputs)
- media queries
- colors
- helpers
  - `sr-only`
  - `@space( x )`
  - `max-width`

Dependencies:
- sass-versioning

**Comment by dominikwilkowski** [comment]
@gazhands please look at the colors and give us feedback. Specifically the primary color :)

**Comment by gazhands** [comment]
[links-list.zip](https://github.com/govau/uikit/files/786291/links-list.zip)

**Comment by gazhands** [comment]
New underline #2DA2BB Looking at primary colour now

**Comment by klepas** [comment]
@gazhands hey, heads up that we still have contrast issues with that bg colour to our text colour.

![screen shot 2017-02-20 at 11 39 28 am](https://cloud.githubusercontent.com/assets/52766/23108452/a87ac4f4-f761-11e6-8b1e-6fcf34e55c09.png)

**Comment by gazhands** [comment]
I don't
![image](https://cloud.githubusercontent.com/assets/17328069/23108870/7c96e3bc-f767-11e6-8430-356abf71caf0.png)

**Comment by gazhands** [comment]
Doesn't matter, we will stay with the original for hover 
![image](https://cloud.githubusercontent.com/assets/17328069/23108890/a564d89e-f767-11e6-8926-871f2f609b31.png)

**Comment by gazhands** [comment]
![image](https://cloud.githubusercontent.com/assets/17328069/23108898/c17ba17a-f767-11e6-89e6-ed50efdff20e.png)

**Comment by klepas** [comment]
This is what we have currently (and it comes from your designs in UI-Kit 1.x):

```
$uikit-colour-Text: #313131 !global;
$uikit-colour-Link: #5bcbe3 !global;
```

If we’re leaving it as-is, @dominikwilkowski this should be unblocked, with no more work to add, yes? (:

**Comment by gazhands** [comment]
new color was for new underline #2DA2BB

**Comment by gazhands** [comment]
color updated
[colors.zip](https://github.com/govau/uikit/files/786394/colors.zip)

**Comment by gazhands** [comment]
Updated colors 
[colors.zip](https://github.com/govau/uikit/files/786541/colors.zip)
