### ISSUE TITLE
new module: form-alerts

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#100]
# design

<img width="447" alt="screen shot 2017-02-16 at 9 34 17 am" src="https://cloud.githubusercontent.com/assets/1266923/22998611/9bf16816-f42b-11e6-84c3-81e695dcbc37.png">

#### Success alert

![image](https://cloud.githubusercontent.com/assets/310330/26033830/5cea2f94-38f6-11e7-9b8d-c79866d171d5.png)
(Source: Business Identity prototype)

#### Info alert
![image](https://cloud.githubusercontent.com/assets/310330/26033845/96b3dc2a-38f6-11e7-82d3-3c9aaff68877.png)
(Source: MyServiceNSW Account)

**Comment by jonathanconway** [comment]
Good to see that you included a non-colour indicator (the 'crossed-out circle' icon) to indicate the kind of error. Useful to colour-blind users!

**Comment by jonathanconway** [comment]
Should there a per-form version of this, which lists out all the errors in the form at the top?

**Comment by dominikwilkowski** [comment]
Hey @jonathanconway The summary version of form-alerts are the page-alerts and have been built already: http://uikit.apps.staging.digital.gov.au/packages/page-alerts/tests/site/

The design here has not been finalised yet. I doubt this is a11y yet :)

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/form-alerts
