### ISSUE TITLE
Review documentation writing style

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#116]
Keep it crazy though!

**Comment by joolswood** [comment]
I'm mainly focused on the Pancake & uikit README.md files. What else should I look at @dominikwilkowski @klepas

**Comment by dominikwilkowski** [comment]
- https://github.com/govau/uikit/blob/master/README.md
- https://github.com/govau/uikit/blob/master/packages/cta-link/README.md (they all have one)
- https://github.com/govau/pancake/blob/master/README.md
- https://github.com/govau/pancake/blob/master/src/pancake.js
- https://github.com/govau/pancake/blob/master/src/pancake-batter.js
- https://github.com/govau/pancake/blob/master/src/pancake-syrup.js
- https://github.com/govau/pancake/blob/master/src/pancake-cream.js
- https://github.com/govau/pancake/blob/master/src/pancake-utilities.js

**Comment by joolswood** [comment]
Leaving pancake for now, as discussed.

Will focus on:

- [ ] https://github.com/govau/uikit/blob/master/README.md
- [ ] https://github.com/govau/uikit/blob/master/packages/cta-link/README.md (they all have one)
