### ISSUE TITLE
new module: media-list

### ISSUE THREAD

**Issue by mgdhs** [govau/uikit#140]
As a user, I'd like to see a nice list with a title, image and description, so I can display something such as news items.

<img width="811" alt="screen shot 2017-03-16 at 15 37 24" src="https://cloud.githubusercontent.com/assets/13895751/23982021/d2339950-0a5e-11e7-9acc-d13fceb47ef5.png">

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/media-list
