### ISSUE TITLE
Date of birth entry 

### ISSUE THREAD

**Issue by gazhands** [govau/uikit#149]
https://trello.com/c/figP8Uhu/40-date-entry-fields

<img width="325" alt="screen_shot_2017-02-14_at_10 58 08_am" src="https://cloud.githubusercontent.com/assets/1266923/24894664/42b7bd76-1ecf-11e7-816c-435ee96d84a1.png">

**Comment by Podgkin** [comment]
what is the benefit of a public GitHub issue linking to a private trello?

**Comment by dominikwilkowski** [comment]
I agree with you @Podgkin and apologize. We have to be better with that. We're doing out best and I will make sure any new issues will come with publicly available resource links

**Comment by Podgkin** [comment]
No worries mate, not critical, just curious

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/date-of-birth-entry
