### ISSUE TITLE
Bug - Footer - Has no top margin

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#150]
When using the footer with a component directly above it there is no gap in-between the component and footer.

To solve this we can add a `margin-top` to the footer. This would likely use the same margin spacing as the header has with it's `margin-bottom`.

Pull request is at #151

**Comment by dominikwilkowski** [comment]
Thanks @alex-page for the issue and PR.
As a rule we add space only to the bottom to make it easier to compose modules. Sorry we didn't documented this yet.

Every module should have it's own space at the bottom.

**Comment by dominikwilkowski** [comment]
I keep your PR open in case you want to update it :)

**Comment by alex-page** [comment]
Thanks @dominikwilkowski I solved this issue by giving margin bottom to my section before the footer.
