### ISSUE TITLE
NPM initial install error

### ISSUE THREAD

**Issue by shaunmac** [govau/uikit#152]
Getting an error after `lerna bootstrap`

ERROR output:
NpmUtilities.execInDir        ("run prepublish", [], "./packages/core")
Error: Command failed: npm run prepublish 
fs.js:81
  throw new TypeError('Expected options to be either an object or a string, ' +
  ^

TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1340:5)
    at ReplaceFileContent (/Users/shaunmacdouagll/Sites/uikit/scripts/helper.js:108:5)
    at Object.sass (/Users/shaunmacdouagll/Sites/uikit/scripts/helper.js:235:4)
    at Object.init (/Users/shaunmacdouagll/Sites/uikit/scripts/helper.js:206:22)
    at Object.HELPER.init (/Users/shaunmacdouagll/Sites/uikit/scripts/helper.js:615:21)
    at Object.<anonymous> (/Users/shaunmacdouagll/Sites/uikit/scripts/helper.js:651:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepublish"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @gov.au/core@0.1.0 prepublish: `node ../../scripts/helper.js precompile publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @gov.au/core@0.1.0 prepublish script 'node ../../scripts/helper.js precompile publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @gov.au/core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../scripts/helper.js precompile publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @gov.au/core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @gov.au/core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shaunmacdouagll/Sites/uikit/packages/core/npm-debug.log

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

> @gov.au/core@0.1.0 prepublish /Users/shaunmacdouagll/Sites/uikit/packages/core
> node ../../scripts/helper.js precompile publish

**Comment by shaunmac** [comment]
npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prepublish' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose run-script [ 'prepublish' ]
5 info lifecycle @gov.au/core@0.1.0~prepublish: @gov.au/core@0.1.0
6 verbose lifecycle @gov.au/core@0.1.0~prepublish: unsafe-perm in lifecycle true
7 verbose lifecycle @gov.au/core@0.1.0~prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/shaunmacdouagll/Sites/uikit/packages/core/node_modules/.bin:/usr/local/bin:usr/local/sbin:/Users/shaunmacdouagll/.composer/vendor/bin:/usr/local/Cellar/php55/5.5.38_11/bin:/usr/local/packer:/usr/local/bin:usr/local/sbin:/Users/shaunmacdouagll/.composer/vendor/bin:/usr/local/Cellar/php55/5.5.38_11/bin:/usr/local/packer:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle @gov.au/core@0.1.0~prepublish: CWD: /Users/shaunmacdouagll/Sites/uikit/packages/core
9 silly lifecycle @gov.au/core@0.1.0~prepublish: Args: [ '-c', 'node ../../scripts/helper.js precompile publish' ]
10 silly lifecycle @gov.au/core@0.1.0~prepublish: Returned: code: 1  signal: null
11 info lifecycle @gov.au/core@0.1.0~prepublish: Failed to exec prepublish script
12 verbose stack Error: @gov.au/core@0.1.0 prepublish: `node ../../scripts/helper.js precompile publish`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:886:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid @gov.au/core@0.1.0
14 verbose cwd /Users/shaunmacdouagll/Sites/uikit/packages/core
15 error Darwin 16.4.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepublish"
17 error node v6.10.1
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error @gov.au/core@0.1.0 prepublish: `node ../../scripts/helper.js precompile publish`
20 error Exit status 1
21 error Failed at the @gov.au/core@0.1.0 prepublish script 'node ../../scripts/helper.js precompile publish'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the @gov.au/core package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     node ../../scripts/helper.js precompile publish
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs @gov.au/core
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls @gov.au/core
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by shaunmac** [comment]
I have installed the latest node and npm

**Comment by dominikwilkowski** [comment]
Hi @shaunmac 

I know you closed this already. Just making sure, don't install the uikit via this repo. Install the modules via npm. This is how to use them and this is how we will support them in the future.

**Comment by shaunmac** [comment]
Hey @dominikwilkowski, thanks for the info. 
So I should not be following this: 
https://github.com/govau/uikit#build

**Comment by dominikwilkowski** [comment]
If you just want to use the uikit please use the description here: https://github.com/govau/uikit#how-to-use

If you want to run the development build and contribute, follow the build steps. :)

**Comment by shaunmac** [comment]
haha I'm not sure I'm at that kind of caliber to contribute, but thank you for the help.
