### ISSUE TITLE
A button class on a link doesn't display properly

### ISSUE THREAD

**Issue by mgdhs** [govau/uikit#162]
`<a href="#" class="uikit-btn">Continue</a>`

Results in a squished button:

<img width="373" alt="a tag with class uikit-btn" src="https://cloud.githubusercontent.com/assets/13895751/25127586/c2432468-2479-11e7-8489-208249c06cc1.png">

It is very common to have links that look like buttons.

**Comment by mgdhs** [comment]
There seem to be two issues here:
- `.uikit-btn` is lacking the layout CSS such `line-height: 48px; display: inline-block;`
- `.uikit-btn` is not as specific as `.uikit-body a`

Locally I've _mostly_ resolved this by adding the layout when on an a and extending to `.uikit-body .uikit-btn`.

**Comment by dominikwilkowski** [comment]
Hey @mgdhs 
Very true and this is by design. We are still missing the whole guidance documentation here which is why you wouldn't know about it. Links should never be styles as buttons. Links are links and buttons are buttons. 
Considering HTML like this:
```html
<a href="#" onClick="something()" class="btn">
```

You should just use
```html
<button onClick="something()" class="btn">
```

This is more accessible and will validate better too :)
However sometimes you want links to big big and bold and need to call them out. That's why we have the [cta-links](http://uikit.apps.staging.digital.gov.au/packages/cta-link/tests/site/) module.

**Comment by mgdhs** [comment]
@dominikwilkowski totally agree that buttons shouldn't _act_ like buttons or be fake buttons with a nasty JavaScript onclick (one of my personal pet peeves). However, having a link look like a button can be useful when you want users to click it because it is associated with an action like 'register' or 'log on' or 'claim'. Here are a few examples:

- https://www.humanservices.gov.au/customer/enablers/online-services/centrelink-online-account-through-mygov
- https://www.humanservices.gov.au/customer/enablers/claiming-dad-and-partner-pay#a2
- https://www.humanservices.gov.au/customer/contact-us/submit-complaint-or-provide-feedback-online

**Comment by dominikwilkowski** [comment]
The a11y concern comes when buttons are used as links non-semantically. The screenreader reads those out differently. More context here: https://marcysutton.com/links-vs-buttons-in-modern-web-applications/

**Comment by mgdhs** [comment]
I totally agree, but I'm talking about a real link, that works exactly like a link, that has link text, that takes you to a page normally, like a link. It is just styled to be more clickable.

`<a href="https://www.humanservices.gov.au/register" class="uikit-btn">Register</a>`

Screenreader says

> "Link [Register](https://www.humanservices.gov.au/register)"

This is also a link in content, on a content website. Not a web application.

I think your guidance should reflect those kind of caveats and best practice but still allow button styling on a link.

**Comment by dominikwilkowski** [comment]
Sorry Mark I get you now. The problem persists though. Links and buttons also have to be styled visually so sighted users know what to expect. I know we ourself have done that in the past but here is use correcting this :)

some links:
- http://www.webaxe.org/proper-use-buttons-links/
- http://getlevelten.com/blog/randall-knutson/design-decisions-buttons-vs-links-fight
- https://www.nngroup.com/articles/clickable-elements/
- http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/
- https://lists.w3.org/Archives/Public/w3c-wai-ig/2016JulSep/0050.html

**Comment by 2metres** [comment]
I tend to side with @mgdhs on this one. There are a multitude of reasons why links might appear as buttons including but not limited to:

- Login/Sign in links in the top right of every modern website
- Multi-step forms
- Styling file input buttons
- Primary CTA's inside of heroes and headers

People will use buttons in this way regardless of wether you want them to or not. Hence the reason why every most major CSS/UI frameworks supports this. Adding 3 lines of CSS to a class is not encouraging people to use these element incorrectly it's centralising the way they do, preventing different ways of overriding in every project.

**Comment by dominikwilkowski** [comment]
I think I've come around and agree with @mgdhs and you. @simonschwartz made a good comment about defensive coding too.

Will "fix" in a minute. :)

Collaboration good ... yay!
