### ISSUE TITLE
text-inputs: Compilation Error in Jekyll

### ISSUE THREAD

**Issue by 2metres** [govau/uikit#164]
```
Jekyll::Converters::Scss encountered an error while converting 'assets/style.scss':
Base-level rules cannot contain the parent-selector-referencing character '&'. on line 15

jekyll 3.4.3 | Error:  Base-level rules cannot contain the parent-selector-referencing character '&'. on line 15
```

This issue popped up after installing @gov.au/text-inputs, If I uninstall it goes away

**Comment by 2metres** [comment]
My Pancake Config
```json
"pancake": {
    "auto-save": true,
    "plugins": true,
    "ignore": [],
    "sass": {
      "modules": true,
      "location": "_sass/vendor/uikit",
      "name": "_uikit.scss"
    },
    "css": {
      "minified": true,
      "modules": false,
      "browsers": [
        "last 2 versions",
        "ie 8",
        "ie 9",
        "ie 10"
      ],
      "location": "assets/css/",
      "name": "uikit.min.css"
    }
  }
```

**Comment by dominikwilkowski** [comment]
Hey @2metres,

I assume your jekyll assets pipeline is throwing an error maybe because of ruby-sass and node-sass incompatibility? I assume it has to do with sass/sass#286.
I suggest you upgrade your Sass version? Let me know if that fixes the issue.

**Comment by 2metres** [comment]
According to my Gemfile.lock I'm on the latest Sass version ([3.4.23](https://github.com/sass/sass/releases/tag/3.4.23)) 

However there is another lib inbetween:
```
jekyll (3.4.3)
    jekyll-sass-converter (~> 1.5.0)
         sass (~> 3.4.23)
```

**Comment by dominikwilkowski** [comment]
Mh... maybe worth using node-sass :)
Pancake has it installed for you already. All you need is a good npm script.
We use the below:

```
"scripts": {
	"build": "node-sass src/sass/main.scss docs/css/main.css --output-style compressed",
	"watch:sass": "npm run build && onchange 'src/sass/*.scss' 'tests/docs/*.scss' -- npm run build",
	"serve": "browser-sync start --server --startPath 'docs' --files 'docs/*.html, docs/css/*.css, docs/js/*.js'",
	"watch": "npm-run-all --parallel serve watch:*",
	"test": "echo \"Error: no test specified\" && exit 0"
},
"devDependencies": {
	"browser-sync": "^2.18.8",
	"node-sass": "^4.5.1",
	"npm-run-all": "^4.0.2",
	"onchange": "^3.2.1"
},
```

Just adjust the paths.

**Comment by 2metres** [comment]
Likely a libsass vs. Sass.rb issue. I thought this had been fixed though ¯\_(ツ)_/¯

Thanks! I might just use the compiled CSS output instead should be good enough for what I'm doing

**Comment by dominikwilkowski** [comment]
Feel free to close this. There is nothing we can do to fix this as the issue lays with Sass directly.

**Comment by chambois** [comment]
Hey folks,

Came across this issue today as well - it seems it's complaining about this code in `/text-inputs/lib/sass/_print.scss`

```
@media print {
	.uikit-text-input {
		border-color: #000 !important;
	}

	&:disabled {
		background-color: $uikit-colour-Background !important;
		border-color: transparent;
	}

	&[disabled] {
		background-color: $uikit-colour-Background !important;
	}
}
```

Is this valid Sass to have the '&:disabled' not nested?

**Comment by dominikwilkowski** [comment]
Are you using ruby-sass @chambois ?

**Comment by chambois** [comment]
Hi Dom,

Yes using Jekyll as per @2metres above.

Shouldn't the Sass be like this?

```scss
@media print {
	.uikit-text-input {
		border-color: #000 !important;

		&:disabled {
			background-color: $uikit-colour-Background !important;
			border-color: transparent;
		}

		&[disabled] {
			background-color: $uikit-colour-Background !important;
		}
	}
}
```

**Comment by dominikwilkowski** [comment]
Are you running into any other issues? Ruby sass is a bit funny with how they implement features. I can add a thing to our roadmap to text all components with ruby-sass but if we find things that are simply not possible such as creating style for each `::disabled` selector (which is valid CSS) then we might need to rethink how we do things.

One possible solution would be to try this:
```sass
:disabled {}
```

or even:
```sass
*:disabled {}
```

**Comment by chambois** [comment]
Thanks Dom this is the only issue we're facing at the moment.

The `*:disabled` selector works - could we suggest to update the `_print.scss` file in the *text-inputs* module with it?  

We're wondering though why we would want to target everything with `*` when we're in a specific module - would we not want to confine the *disabled* styles to just this text-inputs module?

**Comment by dominikwilkowski** [comment]
That's a good point.

As far as print stylesheets go I tend to make everything the same. I would always suggest to seperate the print stylesheets into seperate files via something like https://github.com/Ghostavio/postcss-extract-media

I have a look at this

**Comment by chambois** [comment]
Cool thanks for your help Dom! :)
