### ISSUE TITLE
UI-kit doesn't work on windows

### ISSUE THREAD

**Issue by sitrobotsit** [govau/uikit#175]
Am I right in assuming that the install isn't yet working on Windows because Pancake doesn't support it yet? If so you might like to put that in the install notes in this repo. 

When I run  `npm install @gov.au/body` on my win 10 machine in either powershell or command prompt, get the following error after several minutes:

INFO:    ADDING TOPPINGS TO YOUR PANCAKE VIA @gov.au/pancake-sass
ERROR:   Pancake was unable to create the folder \C:
ERROR:   Error: ENOENT: no such file or directory, mkdir 'C:\C

**Comment by dominikwilkowski** [comment]
Hi @sitrobotsit 

Pancake does not support Windows, that's correct. It's mentioned here:
https://github.com/govau/pancake#requirements

We also have a task open to fix this soon:
https://github.com/govau/pancake/issues/14

We will updated this issue once it is fixed.

**Comment by dominikwilkowski** [comment]
Hey @sitrobotsit 

I just published pancake v1.1.0 and pancake-sass v1.1.0. Both those version now work on my Windows 10 machine here locally now. Can you confirm it works for you now too?

To confirm all you have to do is install any uikit module and see if it errors out sill.

Thanks

**Comment by sitrobotsit** [comment]
Hey @dominikwilkowski 

Yes! All good. At first it failed, I guess cause it was looking at a cached version of pancake. But in a clean folder, everything installed perfectly. 

Thanks for the quick turn around. I can continue to make my job redundant now ;-)
