### ISSUE TITLE
Accordions should require less mark-up

### ISSUE THREAD

**Issue by mgdhs** [govau/uikit#177]
Ideally adding an accordion is simple. Hopefully you aren't doing them too often, or are doing it in a templated way, but I can see people putting the HTML directly in the page.

This is all the markup (from the test) required to get one on the page:

```
<section class="uikit-accordion">
	<a href="#accordion-default" class="uikit-accordion__title js-uikit-accordion" aria-controls="accordion-default" aria-expanded="true" aria-selected="true" role="tab" onclick="return UIKIT.accordion.Toggle( this )">
		Accordion title
	</a>
	<div class="uikit-accordion__body" id="accordion-default" aria-hidden="false">
		<div class="uikit-accordion__body-wrapper">
			Here <a href="#url">is</a> some accordion content
		</div>
	</div>
</section>
```

It is a lot! The more you put in here, the more you have to change if an update occurs.

It also could be more semantic (for the title/heading), and programatically insert some elements. Ideally the mark-up is something like:

```
<section class="uikit-accordion" id="my-accordion-name">
	<div class="uikit-accordion__title">Accordion title</div>
	<div class="uikit-accordion__body">
		Here <a href="#url">is</a> some accordion content
	</div>
</section>
```

This gives you an accordion that is:

- easy to put in the page
- easy to style without JavaScript, and doesn't contain links that don't do anything
- supports doing something more semantic according to the structure of the _rest_ of the page with the title (eg, [a h3](https://www.humanservices.gov.au/ftb))

You then use JavaScript to:
- add the `<a>` _in_ the title
- add the click event to the `<a>`
- toggle classes and set initial ARIA attributes

It is a few lines of jQuery, but a lot more in vanilla JavaScript.

**Comment by dominikwilkowski** [comment]
The problem here is that we try to stay away from javascript frameworks and make our packages work on all of them. That requires us to think about dynamically injections and the state of things.

The markup we came up with is a fine line between convenience and compatibility. You can use it in react as well as in a jquery website.

The HTML is self correcting though once you interact with it. If you do happen to put the wrong arial role on it will be corrected once you open or close it. However we can't force people to use the right aria roles. All we can do is show the best way it should be done and go from there. We do hope a11y tests are being used to test arial roles on integration.

Having said that I like the idea of using a wrapping `section` tag for the accordion. That's just from the tests and the accordion can be use with any markup as long as it doesn't interfere with the styling.

So to reiterate:
- Rendering HTML is impossible to manage with dynamic DOM.
- We do as much as we can to correct mistakes
- The accordion works in react and you can manage the state of it in your own code if you want to

Hope that gives some context.

**Comment by dominikwilkowski** [comment]
We just had a spike with the every charming @elisechant about how we might integrate jquery and react component entry points into the uikit. We came up with a solution that gives you the ability via pancake to select those favours. That will automatically mean the accordion stays as is but will have a flavour that is jquery which means we can manipulate the DOM and add even listeners and aria rols for you. Easy.

Watch this place

**Comment by elisechant** [comment]
The markup is what it is @mgdhs. HTML doesn't have to be lean, it should also be as OOHTML as possible.

**Comment by mgdhs** [comment]
I'm not sure React is your main target audience with the UI toolkit. Have you spoken to any of your users about this? Two versions would be great.

Maybe the title and mentioning jQuery didn't articulate the issue I have with the current implementation. Here is a better list.

# 1. More semantic and accessible title

`<a class="uikit-accordion__title">` likely doesn't give enough structure to a page. "link, some content, link some content" vs "heading x with a link, some content, heading x with a link, some content".

It is also likely not accessible for the same reason.

Ideally the 'title' was an element the accordion didn't directly interact with, but it wraps the `<a>` and gets style. Example: `<h3 class="uikit-accordon__title"><a class="uikit-accordion__control">Accordion title</a></h3>`.

# 2. More programatic where possible

At a minimum, seeing an `onclick` shows that the separation of concerns has likely not been achieved. It is a bit of a flashback to 2005 JavaScript :P Why not do this through `addEventListener`.

This makes updating to a new version easier as it is likely to involve less HTML changes. It also gets closer to something that is easier to insert in the page - you may shudder like I do, but I _bet_ a government department will do this.

**Comment by dominikwilkowski** [comment]
Good points @mgdhs 

Let's get through them together :)
React is a big part of our user base and we need to make sure we don't build something that stops us from transforming government. So with that in mind let's look at the semantics:

```html
<a href="#container">
	The clickable element that will toggle the visibility of the container below
</a>

<div id="container">
	This container has content and other bit in it. Lots of fun.
</div>
```

This to me is the most semantic markup for an accordion. Switch everything off, Javascript and css and you get something that works. The title links to a content bit. It scrolls there to show you what you selected. That's what we do in an accordion. We show you something... or we hide it.
We make no assumptions about your page while you can still add a headline in there if you want to.
An even better HTML markup would use `<details>` and `<summary>` but that unfortunately doesn't work in all browsers and won't let us make it work in them either in an accessible way. E.g. in old browsers this will fallback to divs... no meaning :( also not clickable or even selectable.

Now let's talk about  `onClick` :)
Indeed we used them in the early days of web development and then moved as far away from it as possible. Today, however, we re-embrace it again in application frameworks like Angular or React. That's how fast things move... we are so far we are back where we started :)

Anyway all this exposes a couple issues I take on board now. I think it is important to have a jquery entry point and a react entry point. Both using a vanilla core that we maintain.

In detail this will look like this:

- one vanilla js file with core functionality like `UIKIT.accordion.Toggle()` etc
- one file that is jquery specific that renders an HTML element adding aria roles, and event handlers
- one ES6 jsx file that makes it easy for you to add the component into your react app without making assumptions about your state management

You chose:

- if you use the module in a website where jquery is available => use the jquery version and you have less HTML markup
- if you use the module inside a react app (backend or front end) then use the ES6 jsx file
- if you use none of the above use the vanilla way we have published so far

For us that means we provide value to the biggest two vectors we have plus we don't have to maintain two different implementations while still providing a way for others to use it.

**Comment by dominikwilkowski** [comment]
Hey @mgdhs have a look at 56888e2. First working draft of a jquery entry point.
All files here: 
https://github.com/govau/uikit/tree/feature/jquery-react/packages/accordion/tests/jquery

**Comment by dominikwilkowski** [comment]
Hi @mgdhs 

The accordion has now a jquery entry point and should be close to what you suggested.
Hope it helps
