### ISSUE TITLE
How do I make change the Primary/Hero color?

### ISSUE THREAD

**Issue by 2metres** [govau/uikit#179]
Hey I'm working on a prototype for Medicare and they use green for all of their branding. I cannot for the life of me figure out how to override the colors to generate a green ui kit.

**Comment by dominikwilkowski** [comment]
Hey,
Have a look at this detailed [issue](https://github.com/govau/uikit/issues/178)...
Or:
[You wouldn't believe what people do to change the uikit color.](https://github.com/govau/uikit/issues/178) haha
