### ISSUE TITLE
new module: Dates

### ISSUE THREAD

**Issue by elisechant** [govau/uikit#180]
Dates module that provides formatting methods to format dates as recommended by [DTA's Content Guide](https://guides.service.gov.au/content-guide/numbers-measurements/#dates).

**Comment by elisechant** [comment]
Iteration 1: 

```
const dateFormats = {
    humandayDayMonthYear: 'Tuesday 8 October 2016',
    century: '19th century',
    rangeDayToDay: 'Monday to Friday',
    rangeTimeToTime: '9am to 5pm',
    hours: '9am',
    hoursMinutes: '9:30am',
    hoursMinutes25Hour: '19:45',
    humanisedHoursMinutes: '9 hours and 15 minutes'
};
```

**Comment by elisechant** [comment]
@dominikwilkowski I wonder if the design direction should be more micro like this:  
![screen shot 2017-05-17 at 4 42 26 pm](https://cloud.githubusercontent.com/assets/2195815/26142081/540a1334-3b22-11e7-85a5-e70567221fd9.png)

**Comment by dominikwilkowski** [comment]
Hi @elisechant 

We are moving all suggestions to our community forums. Please join us there to keep the discussion going.

Moved to: https://community.service.gov.au/t/date-formatters
