### ISSUE TITLE
Date formatters required by Dashboards

### ISSUE THREAD

**Issue by elisechant** [govau/uikit#181]
In addition to Content Guide recommended dates referenced here https://github.com/govau/uikit/issues/180, Performance Dashboards Team would like these added: 

```
const dashboardDateFormats = {
	dateTime: `2017-05-10T04:10:19.198Z`, // used in `<time datetime=""`
	dayMonthYear: `1 Feb 2017`,
	monthShortyear: `Feb '17`,
	monthYear: 'Feb 2017',
};

```

**Comment by elisechant** [comment]
cc @nicknelo

**Comment by mgdhs** [comment]
@elisechant how would these benefit everyone else? It looks like these should go in the dashboard application.

**Comment by dominikwilkowski** [comment]
This will be part of a date module in the uikit that comes with the HTML CSS and the js validation. This is just the validation for now and would be the react part of it

**Comment by elisechant** [comment]
@mgdhs it could benefit applications handling dates, beyond Content Guide recommendations.

**Comment by mgdhs** [comment]
Ah ha, I didn't realise this filled the gap in #180 and wasn't dashboard-specific formats.

My only suggestion is to have `dayMonthYear` as `1 February 2017` and maybe a short version `dayShortmonthYear` as `1 Feb 2017`. We use the long format without the week day a lot as it is in the Commonwealth Style Guide.

**Comment by joolswood** [comment]
Sorry if this adds further confusion, but we're also considering including mention of the format that UK uses as examples in forms to the Content Guide (ie `21 6 1989`), but we would specify to only use this when you are giving example in forms. I think this is where Federated Design Clinic landed, right @gazhands ?  Ticketed here: https://github.com/govau/content-guide/issues/126

**Comment by dominikwilkowski** [comment]
Hi @elisechant 

We are moving all suggestions to our community forums. Please join us there to keep the discussion going.

Moved to: https://community.service.gov.au/t/date-formatters
