### ISSUE TITLE
control-input: Label not aligning correctly in Safari (iOS + Desktop

### ISSUE THREAD

**Issue by 2metres** [govau/uikit#184]
![ios safari](https://cloud.githubusercontent.com/assets/924528/25976292/45a26d66-36f7-11e7-937b-6817d2dd1db6.png)

![desktop safari](https://cloud.githubusercontent.com/assets/924528/25976335/8623ed24-36f7-11e7-81bd-2e2380f1239e.png)

**Comment by 2metres** [comment]
I was able to quickly fix it by just adding:
```
.uikit-control-input {
  display: block;
}
```
but not sure if that will cause problems with the checkbox alignment.

**Comment by dominikwilkowski** [comment]
Fixed just now in v0.1.1... You can install it already.. just merging to master now
