### ISSUE TITLE
new module: Autocomplete

### ISSUE THREAD

**Issue by jonathanconway** [govau/uikit#187]
An Autocomplete predicts the word a user intends to enter after only a few characters have been typed into a text input field and provides the user with a set of matching suggestions.

## Design

<img src="https://cloud.githubusercontent.com/assets/310330/26034073/253d3be6-38fa-11e7-8028-184d17ff5290.png" height="80px" />

## Inspiration

<table><tr><td>

<img src="https://designnotes.blog.gov.uk/wp-content/uploads/sites/53/2017/04/location-picker-uk-synonyms.gif" alt="Animated GIF showing a user using a location picker autocomplete field" height="80px" />

Source: <a href="https://designnotes.blog.gov.uk/2017/04/20/were-building-an-autocomplete/">
We're building an autocomplete, Design notes, gov.uk</a>

</td></tr><tr><td>

<img src="https://cloud.githubusercontent.com/assets/310330/26034097/887364e2-38fa-11e7-852b-d1e30fb67fc8.png" height="80px" />

Source: <a href="http://healthdirect.gov.au">Healthdirect</a>
</td></tr><tr><td>

<img src="https://cloud.githubusercontent.com/assets/310330/26034111/d5558fb0-38fa-11e7-885a-14315d9dcc33.png" height="80px" />

Source: <a href="https://www.service.nsw.gov.au/">Service NSW</a>
</td></tr></table>

## Code

Similar open-source projects:

- https://github.com/sparhami/lazy-autosuggest
- https://filamentgroup.github.io/auto-complete
- https://github.com/alphagov/accessible-autocomplete
- https://jqueryui.com/autocomplete/
- https://css-tricks.com/examples/RelevantDropdown/

We could progressively-enhance the HTML5 <a href="https://www.w3schools.com/tags/tag_datalist.asp">datalist</a> element.

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/autocomplete
