### ISSUE TITLE
new module: Phone number entry

### ISSUE THREAD

**Issue by jonathanconway** [govau/uikit#188]
💡 Just giving this a go. It's by no means final. Feel free to jump in and change it.

### Design

<img src="https://cloud.githubusercontent.com/assets/310330/26034185/1a61e81e-38fc-11e7-9c55-5050073a4457.png" height="40px" />

### Inspiration

<table><tr><td>

<img src="https://cloud.githubusercontent.com/assets/310330/26034208/7eee3cf6-38fc-11e7-9531-943511db0a2a.png" height="40px" />

Source: Facebook - Profile

</td></tr><tr><td>

<img src="https://cloud.githubusercontent.com/assets/310330/26034217/a9884be6-38fc-11e7-85d9-f3e3ba5a3972.png" height="60px" />

Source: MyServiceNSW Account - Profile

</td></tr></table>

**Comment by dominikwilkowski** [comment]
Hi @jonathanconway 

We are moving all suggestions to our community forums. Please join us there to keep the discussion going.

Moved to: https://community.service.gov.au/t/phone-number-entry
