### ISSUE TITLE
BEM conformity 

### ISSUE THREAD

**Issue by sitrobotsit** [govau/uikit#193]
In the progress indicator module, I think this;
`<a class="progress-indicator__link progress-indicator--done">`

Should be
`<a class="progress-indicator__link progress-indicator__link--done">`

Because it’s the **progress-indicator__link** element that’s being modified not the **progress-indicator** block.

**Comment by dominikwilkowski** [comment]
That is very true :) and on me!
I shall fix soon. Will be a breaking change though.

**Comment by dominikwilkowski** [comment]
fixed via #234
