### ISSUE TITLE
User testing issue - links aren't visible enough

### ISSUE THREAD

**Issue by mgdhs** [govau/uikit#194]
We've been running some user testing via a third-party company over the last little while. They were testing the new design and implementation of our site, based on the UI toolkit. Their interim report from 22 May 2017 said:

>**Links don't stand out from body text**
> In many cases participants did not initially notice key links within / amongst body text. Participants have indicated that they think links could be clearer or bolder in relation to non-link text.

We've changed our link text to a blue that matches our design, the hover to be a lighter blue, and visited to be a dark grey. There is no perfect colour for this so I haven't submitted a PR.

![link-example](https://cloud.githubusercontent.com/assets/13895751/26534977/9a195f9e-446c-11e7-8496-0dddddc32cd6.png)

**Comment by gazhands** [comment]
Thanks for the feedback Mark. This is something that hasn't come up in testing here at the DTA and maybe a symptom of content presentation and IA. Improving how 'key links' are presented with a good content strategy could help this. We'll also look in to how we might improve links within body text.

**Comment by dominikwilkowski** [comment]
Hi @mgdhs 

This should be fixed now with the new body version 1.0.0. Please have a look here: https://gold.service.gov.au/components/body/
