### ISSUE TITLE
Buttons and body clash with defaults

### ISSUE THREAD

**Issue by steveworley** [govau/uikit#197]
I just came across a bit of an issue with the default settings when using multiple modules together.

```
$uikit-colour-Font: #313131;
$uikit-colour-Secondary: #313131;
```

The `body` module provides a style for all links in `.uikit-body a` which supersedes the uikit button style which only references `.uikit-btn--secondary`. `.uikit-btn` sets the font colour but is not specific enough.

Should the button styles for links be more specific so they're not lost when the body module is used?

Here are some examples:

![image](https://user-images.githubusercontent.com/1840912/27060107-ec67085c-501d-11e7-92ff-bf51257ad2f3.png)

![image](https://user-images.githubusercontent.com/1840912/27060132-1531a92c-501e-11e7-8cdb-c2195f9b52e5.png)

**Comment by dominikwilkowski** [comment]
Thanks for reporting this @steveworley 

We didn't catch this as buttons were not supposed to be links :) but buttons. I recently gave in via #162 but would still strongly suggest to use buttons where you mean "buttons".

In the meantime we will fix this. :)
