### ISSUE TITLE
new module: body

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#2]
- native html tags
  - `hr`
  - `kbd`
  - `del` and `ins`
  - highlight colour
  - `abbr`
  - etc.

**Comment by klepas** [comment]
- [ ] abbr
- [ ] kbd
- [ ] del
- [ ] ins
- [ ] hr
- [ ] highlight colour
- [ ] …

**Comment by klepas** [comment]
Additionally:

- [ ] Dom: “I think we should rename all globals in core to `uikit-[name]` and take the `core` out. Only for core module. kinda makes sense and makes things shorter”

**Comment by klepas** [comment]
Pulling the `.abstract` stuff out and leaving it planted here for now/future reference copy pasta:

```
//--------------------------------------------------------------------------------------------------------------------------------------------------------------
// `.abstract` page/header/article lead-in
/**
 * Abstract/introductions.
 */
@mixin abstract {
	font-size: 1.1875em;//19 from 16
}

.abstract {
	@include abstract;
}
```

**Comment by klepas** [comment]
Remaining todos:

- [ ] add missing readme
- [ ] add missing changelog

**Comment by elisechant** [comment]
can we puhleeease not style raw elements?

**Comment by dominikwilkowski** [comment]
We include normalizer in there will be some normalization going on on raw tags. We just extend this styling with uikit flavor but no breaking changes.

**Comment by dominikwilkowski** [comment]
Have a peek: https://github.com/govau/uikit/blob/develop/packages/body/src/sass/module.scss

**Comment by dominikwilkowski** [comment]
Uh and also remember the body module is optional ;)

**Comment by dominikwilkowski** [comment]
- [ ] Add back external link icon

**Comment by klepas** [comment]
That task is reliant on #28

**Comment by klepas** [comment]
Noting: https://github.com/govau/uikit/issues/1#issuecomment-280958810
