### ISSUE TITLE
Confusion with gov.au UI Kit (version 1)

### ISSUE THREAD

**Issue by marblegravy** [govau/uikit#208]
I believe there's a lot of confusion around about UI-Kit as most people do a google search and end up at https://gov-au-ui-kit.apps.staging.digital.gov.au/ or https://guides.service.gov.au/design-guide/ rather than this one. 

Is there a plan to update the messaging or decommission these old pages to point to this one to avoid confusion?

**Comment by dominikwilkowski** [comment]
Very true and a concern of ours as well. We are building currently a website that will address all this. But because there has been so much disruption here we're just now getting on our feet again to start building a team again. Please stick with us and stay tuned :)
