### ISSUE TITLE
new module: primary-nav

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#21]
# code

- [ ] variation for the hamburger to be left or right

# uikit 1

<img width="932" alt="screen shot 2017-02-16 at 8 58 33 am" src="https://cloud.githubusercontent.com/assets/1266923/22997446/840ec522-f426-11e6-8714-f8ebe1617faa.png">

[Design guide](http://guides.service.gov.au/design-guide/patterns/navigation/index.html#site-navigation)

**Comment by klepas** [comment]
This is blocked b/c we have issues with the current site-nav, and have some new designs from @gazhands that we need to discuss together.

**Comment by gazhands** [comment]
![2 content template copy](https://cloud.githubusercontent.com/assets/17328069/22907672/61bdf382-f29e-11e6-9114-d429d738848c.png)
![768px](https://cloud.githubusercontent.com/assets/17328069/22907670/61b985a4-f29e-11e6-8f61-29a6245ca072.png)
![2 content template](https://cloud.githubusercontent.com/assets/17328069/22907671/61ba900c-f29e-11e6-8e50-091efaec3ca2.png)
![content guide - home](https://cloud.githubusercontent.com/assets/17328069/22907673/61c7c704-f29e-11e6-9a14-8f87bcd1d737.png)

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/navigation
