### ISSUE TITLE
Export react templates as es modules or umd 

### ISSUE THREAD

**Issue by elisechant** [govau/uikit#210]
so they can be required without needing to load them through babel

something like this: 

`"build:lib": "babel src/ -d lib --source-maps --copy-files",`

Otherwise they need to be explicitly required by babel: 

![screen shot 2017-07-06 at 11 38 49 am](https://user-images.githubusercontent.com/2195815/27891881-c3349a56-623f-11e7-9307-c43b8c52e8ea.png)

**Comment by dominikwilkowski** [comment]
This should also be fixed now.
