### ISSUE TITLE
Location of pancake directory doesnt work out of the box with CRA

### ISSUE THREAD

**Issue by elisechant** [govau/uikit#212]
![screen shot 2017-07-06 at 11 30 51 am](https://user-images.githubusercontent.com/2195815/27891706-a6a4a6c0-623e-11e7-840d-f2d7808d8beb.png)

**Comment by dominikwilkowski** [comment]
Hey @elisechant 

sorry for the late reply :)
Pancake won't be able to run with CRA out of the box without config as there are too many other use cases.

To get the UI-Kit to work all you need to do is to adjust the path for your pancake folder:

```json
"pancake": {
	"react": {
		"location": "src/_uikit/"
	}
}
```
