### ISSUE TITLE
Update 'How to use' documentation

### ISSUE THREAD

**Issue by TrebBrennan** [govau/uikit#219]
https://github.com/govau/uikit#how-to-use
Seperate yarn/NPM from each other. It sounds like both are needed.

Uikit documentation needs to be rewritten as pancake is installed as a dependency. Users don't need to know anything about pancake...

**Comment by alex-page** [comment]
Thanks @TrebBrennan I am looking into bundling this with a couple of changes.

**Comment by iijiang** [comment]
pretty clear to me :). I just npmed one.

**Comment by iijiang** [comment]
this is another thing I would like to mention is, for a uikit user, I might just need a starter package, could I just get a vanilla package as bootstrap does?

**Comment by alex-page** [comment]
@iijiang This is something we are hoping to include in the near future. The barrier to entry for some users is currently too high and people would likely want to use a simplified version for prototyping. 

Currently the [uikit-starter](https://github.com/govau/uikit-starter) would be the best option.
