### ISSUE TITLE
Document ways of working

### ISSUE THREAD

**Issue by TrebBrennan** [govau/uikit#222]
Team agree on methods or framework for documentation of components as they are being developed.

## Definition of done
- [x] Proposed framework based on #221 
- [x] Share back to agree
- [x] Documentation shared

**Comment by gazhands** [comment]
This ?
**Checklist consideration**

- Research - Current examples
- Usability requirements
- Accessibility requirements
- Concepts
- Prototype testing
- A11y review
- Content review
- Tech review
- Prepare documentation for build

**Comment by gazhands** [comment]
Guidance and how to contribute?
https://docs.google.com/document/d/1Ozkl5JF-EloY8xYDsrESPBFWC-ODgIDs1cGt-J-R4MI/edit
