### ISSUE TITLE
System fonts

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#232]
Remove open sans and all instances of the google fonts.

During research we have met many Australians who live in rural and remote areas where internet access is limited but Government services are still required. Using system fonts makes the load times faster with only a slight compromise on aesthetics.

System fonts have come a long way. Manufacturers are now shipping some elegant fonts with their main platforms. Major websites (github) and design systems (bootstrap) have embraced them.

**Comment by mgdhs** [comment]
:+1:

This one bit us recently. We were no longer downloading the font file but had references it in the CSS (eg, the headings). Something else on our site started downloading the font file and changing a few pages on the site.

**Comment by imperator99** [comment]
Thanks @alex-page, this is interesting. Fallbacks are great but only useful if the primary font doesn't download _at all_, rather than just slowly.

**Comment by alex-page** [comment]
This is implemented, will be released soon.
