### ISSUE TITLE
new module: page-alerts

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#24]
# design

<img width="670" alt="screen shot 2017-02-16 at 9 34 23 am" src="https://cloud.githubusercontent.com/assets/1266923/22998547/637d452c-f42b-11e6-8581-1a75bc752b12.png">

# code

- [ ] notifications in four variations: info, success, alert and error

**Comment by klepas** [comment]
Work off from the awesome work @TrebBrennan started at https://github.com/AusDTO/gov-au-ui-kit/blob/dashboard/validation-test/assets/sass/components/_form-validation.scss
