### ISSUE TITLE
package should not be creating top level directories

### ISSUE THREAD

**Issue by davidgilbertson** [govau/uikit#251]
I have just installed core (`npm i @gov.au/core`) and I now have a `/pancake` directory at the top level of my project.

I don't want npm packages creating directories in my project. Can I safely delete this?

**Comment by dominikwilkowski** [comment]
Yes it is a artefact of the build. You can delete the folder, disable the creation, move it somewhere else etc.

More infos here:
https://github.com/govau/pancake
