### ISSUE TITLE
Relation to the YOOtheme UIkit?

### ISSUE THREAD

**Issue by rooby** [govau/uikit#279]
This might be a useful question for the FAQ as it could be a point of confusion...

How (if at all) does this project relate to the existing YOOtheme UIKit project (https://getuikit.com/ - https://github.com/uikit/uikit)?

**Comment by alex-page** [comment]
Hey @rooby 😀 

There is no relation to the Uikit project. (https://getuikit.com/)

We are currently rebranding the whole UI-Kit as the current naming isn't very interesting, has poor SEO and doesn't describe the community, research and all the extras that make up our design system.

I will check with the team, about adding this into the FAQ file, as this is the first instance I know of it being brought up.

**Comment by rooby** [comment]
Cool, thanks

**Comment by alex-page** [comment]
@rooby We have renamed all of the repositories and websites ( uikit.service.gov.au ). Thanks for the feedback!
