### ISSUE TITLE
Inconsistent heading margin when proceeded by a paragraph

### ISSUE THREAD

**Issue by mgdhs** [govau/uikit#282]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened

When viewing a page with headings for structure and a mix of tables, paragraphs and lists, the space around headings becomes in consistent.

Example: https://www.humanservices.gov.au/individuals/enablers/claiming-abstudy

The 'how to claim' heading 2 has a significant margin-top because it is after a paragraph.

The 'closing dates' heading 2 has no margin-top on the element which results in a visually different gap to the user. This is because it is proceeded by a list.

The cause of this is `p + .uikit-display-#{$i} { margin-top: uikit-space( 1 ); }` from [799de9a](https://github.com/govau/uikit/commit/799de9a4ae8e24aeb75f5acf7cdbf80a097d52e0) in the headings module. The issue this commit comes from seems unrelated to headings - this seems like an unintended change.

An external review of our website picked it up.

## What I expected to happen

Headings should have a consistent margin, regardless of elements around it.

If there is a requirement for different spacing in the 'in-page-nav', it is contained to that module and more specific.

# Reproducing

- Module name: Headings
- Module version: 0.3.0
- Pancake version: 1.0.6
- Node version: 8.1.3
- npm version: 5.0.3
- Pancake settings in your `package.json`:

```
  "pancake": {
    "auto-save": true,
    "plugins": true,
    "ignore": [],
    "css": {
      "minified": true,
      "modules": false,
      "browsers": [
        "last 2 versions",
        "ie 8",
        "ie 9",
        "ie 10"
      ],
      "location": "sass/pancake/css/",
      "name": false
    },
    "sass": {
      "modules": true,
      "location": "sass/pancake/",
      "name": false
    },
    "js": {
      "minified": false,
      "modules": false,
      "location": "js/pancake/",
      "name": "pancake.js"
    },
    "react": {
      "location": "pancake/react/"
    }
  },
```

Steps to reproduce:

1. Go to a page with headings and other content.
2. You'll notice the gaps above headings are different depending on what element is before it.

**Comment by TrebBrennan** [comment]
@mgdhs Thanks for reporting the issue, good pick-up. 👍 
I think we could unpack the issue further:

The `H2` element having a different margin-top when proceeding a `P` element **was intentional** - but only in long sections of content - as it provides a visual break in text where headings appear and helps improve the legibility.

In your example it's clearly not working correctly and needs to be fixed.
I think what needs fixing is the margin not appearing after the lists or other content.

**A hot fix might look like this:**
Where we suppress the margin-top to a particular container, and all `h2` elements proceeding something have a consistent margin.

```
.main-content {
* + .uikit-display-#{$i} { margin-top: uikit-space( 1 ); }
}
```

** Next steps **
Unless anyone else wants to chime in around it, I'll add it to the backlog and we'll look at it soon.

**Comment by mgdhs** [comment]
@TrebBrennan I couldn't find any location where it described that it was intentional. Is this the type of info that'll eventually appear in a design guide?

Your suggested fix is nice and normalises it a bit. When playing with it in the example page, a h2 next to a h3 maybe has too much gap. You could call this a content problem. An overly complicated fix could be:

```
.main-content {
  *:not([class^="uikit-display"]) + .uikit-display-#{$i} { margin-top: uikit-space( 1 ); }
}
```

**Comment by TrebBrennan** [comment]
Yeah, we do intend to pull together that level of documentation at some stage. We'd be keen to get your input on that when we get up to it if you're open to it?

Yeah that `:not` selector looks like it would help with the consistency. Noting we support ie8 and I think [':not' wasn't supported back then?](http://caniuse.com/#feat=css-sel3) :(

Someone from the team will likely reach out to you when we pick up this bug, but in the meantime if you have any more info or thoughts on a solution please share :) Thanks Mark.

**Comment by mgdhs** [comment]
We'll have a go at fixing this locally and put a PR up.

`:not` isn't supported by IE8 but this isn't functional or a deal breaker if it doesn't work.

**Comment by dominikwilkowski** [comment]
We should have addressed this issue now with our [owl selector](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls) in our new 1.0.0 version. Please reopen this issue or submit a new one if we have missed anything.
