### ISSUE TITLE
new module: accordion

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#29]
# uikit 1

<img width="749" alt="screen shot 2017-02-16 at 9 26 08 am" src="https://cloud.githubusercontent.com/assets/1266923/22998238/f6de17c6-f429-11e6-8c28-4f3e77c95f78.png">

[Design guide](http://guides.service.gov.au/design-guide/components/accordions/index.html)

**Comment by mgdhs** [comment]
It would be nice if the new accordions had a few more advanced features we're looking for:

- worked independent of markup (we get this out of the box in 2.0)
- are nestable (accordions containing accordions)
- remembered the state and return the user to that state (expand x, leave the page, go back to the page, x is expanded)
- be linkable (link to x and have it expanded and focused)
- display as an accordion in mobile only (in desktop they are a panel)
