### ISSUE TITLE
...attributeOptions documentation in `README.md` for components

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#297]
In #295 @rhubarbselleven explained that the documentation for disabled was missing. This showed us that it is not clear that users can add properties to react components by using the spread operator.

The documentation should be updated to clearly explain this. There should probably also be some per component examples e.g. `select` and `disabled`.

**Comment by dominikwilkowski** [comment]
I'd argue that we have enough docs about this in the readme.

Each readme for each component has this line:

> (💡 additional props are spread onto the component)

We will add more infos into the docs website

**Comment by rhubarbselleven** [comment]
Using the attribute spread I think is fine and a consistent pattern in this toolkit. For me, the unclear part was specifically with `select` when defining `option`s as a json object. It was unclear if the attributes would follow through when declaring the children from the parent.

**Comment by dominikwilkowski** [comment]
🤔  yeah fair enough. We spread into wrapper for nested children by by making the user call the object the same as the wrapper for a conscious choice like this:
https://github.com/govau/uikit/blob/develop/packages/link-list/tests/react/index.js#L39

```jsx
<AUlinkList className="additional-class" items={[
	{
		link: '#options',
		text: 'Options',
	},
	{
		link: '#help',
		text: 'Help',
		className: 'test-class',
		li: {
			className: 'test-class test-class--mod',
		},
	},
	{
		link: '#signout',
		text: 'Sign Out',
		className: 'test-class test-class--mod',
		li: {
			className: 'test-class',
		},
	},
]} />
```

This will render out:

```html
<ul class="au-link-list additional-class">
	<li><a href="#options">Options</a></li>
	<li class="test-class test-class--mod"><a href="#help" class="test-class">Help</a></li>
	<li class="test-class"><a href="#signout" class="test-class test-class--mod">Sign Out</a></li>
</ul>
```

I wonder if this is consistent enough for select:

```jsx
<AUselect id="test2" className="testing" options={[
	{
		value: '',
		text: 'Please select',
	},
	{
		value: '1',
		text: 'Option 1',
		className: 'testing',
	},
	{
		value: '2',
		text: 'Option 2',
	},
]} />
```

which will render:

```html
<select class="au-select testing" id="test2">
	<option value="">Please select</option>
	<option value="1" class="testing">Option 1</option>
	<option value="2">Option 2</option>
</select>
```

So when you're in the listing context you have control over that item, whatever it is. If that item will render a wrapper element it will give you that wrapper element as an object where you can spread things into it yourself.

Thoughts?

**Comment by rhubarbselleven** [comment]
I think it's great syntactic sugar, it does simplify the approach to making lists of stuff which is a common pattern. From a documentation point of view it does need a hint that the children get expanded into the specific type. Eg: knowing that `options` gets expanded into [`AUselectItem`](https://github.com/govau/uikit/blob/3108d4ef077647a08baf570a016c594b33c86412/packages/select/src/js/react.js#L52) and thereby `disabled` or `selected` means something.

What occurs here as a part of the component rendering? With this approach and rendering a giant list, what can we expect on subsequent renders?

**Comment by dominikwilkowski** [comment]
We just launched the https://gold.service.gov.au/ website that now has more information around this. It is the start for more and more information coming now.

Even though the information there are not complete just yet we are adding more every day. I close this issue as most should be explained there. Please feel free to reopen or submit a new one if we have missed anything.

Thank you
