### ISSUE TITLE
new module: header

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#30]
# design

- [ ] new design to be nailed

# uikit 1

<img width="674" alt="screen shot 2017-02-16 at 9 10 41 am" src="https://cloud.githubusercontent.com/assets/1266923/22997746/cf09e164-f427-11e6-9f7c-e881fa4ddd10.png">

[old design guide](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-page-header.html)

**Comment by klepas** [comment]
Noting this is *not* blocked by #21, since the site-nav will be an optional feature of the header.

**Comment by mgdhs** [comment]
The site title in the header should *not* be a `<h1>`.

Generally it's considered bad practice to have these as headings. There are however, some differing opinions. The [W3 says](https://www.w3.org/WAI/tutorials/page-structure/headings/) (emphasis mine):

> When looking at the content, the highest available heading level should be used to mark up the **heading of the main content**, as this makes it easy to discover.

Some of the confusion may come from the [module doco](http://uikit.apps.staging.digital.gov.au/packages/header/tests/site/) saying 'page title' not 'site title'.

When simply changing this from a heading, it doesn't look the same.

Do you want a separate bug/PR or is this feature still a work in progress?

**Comment by dominikwilkowski** [comment]
I will make this a seperate issue so we can track it :)

**Comment by klepas** [comment]
My bad iirc.
