### ISSUE TITLE
Accordion does not expand when accordion body has a border/padding

### ISSUE THREAD

**Issue by roflcopterDorrie** [govau/uikit#300]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

When the accordion body has padding or a border, the according does not expand.

## What happened

The accordion doesn't expand. 
 - Classes do not change from uikit-accordion--closed to uikit-accordion--open.
 - display: block is briefly applied, then disappears 

## What I expected to happen

The accordion to expand with classes changing and display:block being applied correctly.

# Reproducing

- Module name: accordion
- Module version: 0.3.0
- Pancake version: 1.1.0
- Node version: 6.10.3
- npm version: 3.10.10
- Pancake settings in your `package.json`:
```
"pancake": {
    "auto-save": true,
    "plugins": true,
    "ignore": [],
    "css": {
      "minified": true,
      "modules": false,
      "browsers": [
        "last 2 versions",
        "ie 8",
        "ie 9",
        "ie 10"
      ],
      "location": "css/",
      "name": false
    },
    "sass": {
      "modules": false,
      "location": "sass/vendors/",
      "name": "uikit.scss"
    },
    "js": {
      "minified": true,
      "modules": false,
      "location": "pancake/js/",
      "name": "pancake.js"
    },
    "react": {
      "location": "pancake/react/"
    }
  }
```

Steps to reproduce:

1. Setup your accordion.
```
<div class="uikit-body js">
  <div id="view-transcript">
    <div aria-controls="transcript-body" onclick="return UIKIT.accordion.Toggle( this )" class="uikit-accordion__title uikit-accordion--closed">Read transcript</div>
    <div class="uikit-accordion__body uikit-accordion--closed" id="transcript-body">
      <p><strong>00:00</strong> (relaxing music)</p>
      <p><strong>00:10</strong> Something else blah blah</p>
    </div>
  </div>
</div>
```

2. Add a border or padding to the accordion body
```
#transcript-body {
  border: 2px solid blue;
}
```

3. Click the accordion toggle

**Comment by dominikwilkowski** [comment]
Thank you for this very detailed issue. this makes it very easy for us to follow up.
Until we have time to investigate this issue and possibly fix, is it easy for you to just add another `div` inside `uikit-accordion__body` and add the padding tho that div instead? I think this should fix your issue.

**Comment by roflcopterDorrie** [comment]
Yep, that is what I have done as a workaround for now. Cheers

**Comment by dominikwilkowski** [comment]
Hi @roflcopterDorrie 

I had a look and it is highly inefficient for any library to detect any spacing of the container and take it into account of that size calculation. Even jQuery doesn't do it. :)

I close this for now as you can easily archive it by wrapping your content in another element and apply the padding/margin there.

Thanks for the issue and please let us know any other things you come across.
