### ISSUE TITLE
Documentation: FAQ line: 129 - Unclear sentence.

### ISSUE THREAD

**Issue by alan-cole** [govau/uikit#301]
In FAQ.md, line 129:

> There are always going to be gaps as the framework is help intentionally lose to help as many different platforms.

This sentence does not make sense and should be revised to better explain it's statement.

**Comment by TrebBrennan** [comment]
Thanks for finding that one Alan.

We've just now revised that text with PR:302 which [you can see here](https://github.com/govau/uikit/pull/302/files). 

We hope to merge it with master in the next week.
