### ISSUE TITLE
You cannot simply override a button property (say, border colour on a secondary button) because of specificity

### ISSUE THREAD

**Issue by jonathaningram** [govau/uikit#303]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened

You cannot simply override a button property (say, border colour on a secondary button) because of specificity. 

## What I expected to happen

Passing in one's own `className` allows me to override styles.

# Reproducing

- Module name: buttons
- Module version: 1.0.0-next.7

Steps to reproduce:

1. Go to https://gold.apps.y.cld.gov.au/components/buttons/#secondary-buttons
2. Inspect the first secondary button in dev tools.
3. Add a class named `foo` to it in the dev tools.
4. Add a style rule `.foo { border-color: red }`
5. Observe that the border does not change.
6. Change your style rule to `.au-btn.foo { ... }`
7. Observe that it now does change.

# Attachments

![image](https://user-images.githubusercontent.com/626664/36400430-ed09ec8e-1624-11e8-8adb-2b557d44e690.png)

![image](https://user-images.githubusercontent.com/626664/36400438-f809faa2-1624-11e8-80d7-3776c7cdcd18.png)

![image](https://user-images.githubusercontent.com/626664/36400442-fdeb29b4-1624-11e8-8b80-8a7a4a83a184.png)

# What you might say

1. Perhaps the `.au-btn` is needed on your end for some specificity reasons.
2. I shouldn't be trying to style like this, but rather should be customising SASS variables or something.

Thoughts?

**Comment by alex-page** [comment]
@jonathaningram Thanks for the feedback, we have had this feedback a few times so we definitely need to explain this better to our community. 

The recommended way to override the colours in the buttons or other components is using sass and structuring your project in a specific way.

The uikit uses `!default` on variables which can be overridden. In your case you are trying to change the `$AU-color-foreground-action` variable. If you set `$AU-color-foreground-action: red;` above where you import the uikit sass it will flow through the entire system.

This file below would be your `style.scss` which would be compiled into a `style.css` file:
```
// Here we override the colours in the uikit
@import 'base/colors';

// Here we import the uikit
@import '../_uikit/sass/uikit';
```

A working example of this can be seen here:
https://github.com/govau/GOLD/blob/develop/src/sass/style.scss

**Comment by jonathaningram** [comment]
@alex-page cool thanks. I suspected the way to do it was customising the SASS.

**Comment by jonathaningram** [comment]
@alex-page by the way, some background on why I'm doing this: I'm using styled-components which are the thing that add in their class name (they are the "`.foo`" in the above). In this way, I'm using ui-kit as the base styles, but I'm customising things to suit the app (because I'm prototyping and replicating existing styles).

**Comment by alex-page** [comment]
@jonathaningram That is frustrating. In the future we should look into styled components and how we can support them better. 

We do offer an option to export each of the components `sass` into individual modules. You can see this in `pancake`. This would allow you to choose a folder for each components sass to go into as an individual module. You could then import the component sass and override as needed.
