### ISSUE TITLE
How do I stop pancake from installing things into my project?

### ISSUE THREAD

**Issue by jonathaningram** [govau/uikit#304]
When I installed the buttons module (`{ "@gov.au/buttons": "^1.0.0-next.7" }`), a postinstall script added a `pancake` stanza to my package.json and also created a `pancake` folder.

What is the recommended way to disable pancake or make it opt-in?

**Comment by alex-page** [comment]
@jonathaningram This is currently lacking documentation in the uikit as it's a seperate project.

Simply said in your `package.json` pancake creates an object. In this object you can choose how to add each component to your project. You can read more documentation here:
https://github.com/govau/pancake#local-settings

Depending on your projects needs you can get sass, react, minified css, minified js etc. If you don't want a specific file you can make the `name: false`.

**Comment by jonathaningram** [comment]
@alex-page what if the project doesn't need to use pancake? Are the options to either a) disable postinstalls or b) just manually remove the pancake things after I `yarn add @gov.au/foo --save`?

**Comment by alex-page** [comment]
@jonathaningram not currently. You can remove the package.json object and the `node_module` files if you want. This will be a bit frustrating on every use.

@dominikwilkowski any ideas about this?

**Comment by dominikwilkowski** [comment]
You can easily disable pancake all together by adding the below code into your `package.json` file:

```json
{
  "name": "your-name",
  "version": "0.1.0",
  "pancake": {
    "auto-save": false,each run
    "plugins": false
  }
}
```

Hope it helps @jonathaningram

**Comment by jonathaningram** [comment]
Cheers @dominikwilkowski
