### ISSUE TITLE
Default import name is AUbutton, for example, which has stutter

### ISSUE THREAD

**Issue by jonathaningram** [govau/uikit#305]
While one can generally import the default module in whatever name you want, some feedback:

I was wondering is it really necessary for the library to actually use names like `export default AUbutton;`?

Again, one can import with whatever name one wants, but the reason I raise this is that my initial reaction is to write my import with more idiomatic case like this:

```js
import AuButton from "@gov.au/buttons";
```

(I say idiomatically as in: it's uncommon to import React components named `AUlowercaseletterhere`

Notice the case is different to your default export name. 

Aside: I'm actually importing it in a wrapper component inside my application.

Anyway, aside from the casing (this is not about bikeshedding!), there is stutter on your recommended imports:

```js
import AUbutton from '@gov.au/buttons';
_______^^_________________^^
```

We essentially have "gov" in there twice.

How about just:

```js
export default Button;

// ... later
import Button from '@gov.au/buttons';
```

Less typing, less to read, and all that.

Just a suggestion really, this doesn't affect me significantly.

**Comment by alex-page** [comment]
@jonathaningram We used to not prefix our components with `AU` and they were always called `Button`, `Accordion` or `SomethingElse`. The issue with this was that when a user wanted to create there own custom `Button` there would be a duplicate component name when they import the `Button` from the uikit. We decided the best option was to prefix our components with `AU`.

Hopefully this gives some context for why it is how it currently is. I'll try and give a more detailed answer in the next few days.

**Comment by dominikwilkowski** [comment]
Hey @jonathaningram 

Thank you for talking me through this issue. I toally agree that it would have been nicer to keep them names shorter. I even set out to make that change but upon realizing how many things it would effect decided to leave it. The outcome simply doesn't justify the effort in the end. You can always use: `import AUButton as Button from 'gov.au/buttons'` later on.

Maybe we get some time and space in the future to change it.

Please keep all your thinking coming. It really does help us make better decisions in the future.
