### ISSUE TITLE
Footer example could be more useful

### ISSUE THREAD

**Issue by jonathaningram** [govau/uikit#307]
It's more common than not to have more than one link, so the example could show how to do that:

![image](https://user-images.githubusercontent.com/626664/36509986-9fc11794-17b5-11e8-8b10-70212c68d734.png)

**Comment by alex-page** [comment]
@jonathaningram this is definitely an issue, we feel this pain in balancing a consistent layout and large components in the example section. This is also likely an issue on the grid, header and footer.

You can see a full width example of a footer here:
https://uikit.service.gov.au/packages/footer/tests/site/

**Comment by jonathaningram** [comment]
Cheers @alex-page that's useful. Feel free to close or keep open if you want to revisit.
