### ISSUE TITLE
Is LinkList meant to be able to be used standalone?

### ISSUE THREAD

**Issue by jonathaningram** [govau/uikit#308]
As you can see in this CSS the correct padding will only be applied if I have the `.au-body` class on my body, which I'm not planning on using (at least at this stage):

![image](https://user-images.githubusercontent.com/626664/36511860-770947e8-17bc-11e8-81f4-df98524f5683.png)

Is there any reason the padding and margin lines are not just directly in the exact `.au-link-list {}` stanza?

**Comment by dominikwilkowski** [comment]
Hey @jonathaningram 

Yes the link list depends on body: https://github.com/govau/uikit/blob/master/packages/link-list/package.json#L66
