### ISSUE TITLE
Accordion arrow icon is incorrectly positioned in ie8.

### ISSUE THREAD

**Issue by TrebBrennan** [govau/uikit#309]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened

The Accordion arrow icons are incorrectly positioned in ie8.
(Noting that UI-kit supports ie8 and understanding that "support" can mean a variety of things, this currently looks broken and negativity impacts the UX for this component )

## What I expected to happen

Arrow should be positioned within the `.au-accordion__title` element.

# Reproducing

- Module name: accordion
- Module version: 1.0.0

# Attachments

![screen shot 2018-02-22 at 3 49 39 pm](https://user-images.githubusercontent.com/15899197/36521087-f9b2ac9e-17e8-11e8-96be-2f1466a485b3.png)

**Comment by alex-page** [comment]
I am looking into this today. Thanks @TrebBrennan
