### ISSUE TITLE
AU-fontgrid doesn't allow me to use values not inside AU-fontsizemap

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#318]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened
I wanted to use `AU-fontgrid( 18px );` however it only takes values from inside the `AU-fontsizemap`. The `AU-fontgrid` function should be able to support `pixel` values.

## What I expected to happen
The function is ran and I get a result that snaps to the `AU-unit`:
```
@include AU-fontgrid( 18px ); // using default 1.5

fontsize: 18px;
fontsize: 1.125rem;
lineheight: 1.555;
```

# Reproducing

- Module name: core
- Module version: 1.0.1

Steps to reproduce:

1. Use `AU-fontgrid` without a value from inside `AU-fontsizemap`

**Comment by dominikwilkowski** [comment]
Is this maybe a feature request and should this be discussed in the community forum in core? As it increases the API surface.

**Comment by alex-page** [comment]
Sounds good i'll add it to the community
