### ISSUE TITLE
new module: progress-indicator

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#32]
# design

<img width="262" alt="screen shot 2017-02-16 at 9 39 34 am" src="https://cloud.githubusercontent.com/assets/1266923/22998664/ded7d6ce-f42b-11e6-9a41-833de8a40e04.png">

# code

- [ ] add classes and different html for each step: pending, in-progress and done

**Comment by klepas** [comment]
We need access to artefacts for this, and we should define the use case somewhere too.

**Comment by klepas** [comment]
Specifically want to look at artefacts from marketplace and mygov work, and decide which we want to use/and how to define it’s use cases.

**Comment by gazhands** [comment]
https://trello.com/c/DpaURbPy/19-progress-indicator

**Comment by gazhands** [comment]
look at fallback for icons
