### ISSUE TITLE
Starter kit doesn't work

### ISSUE THREAD

**Issue by jsephora** [govau/uikit#320]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened
- Clicked on 'Get Started'
- Click 'Use our starter pack on GitHub' button
- Installed as per instructions
- A page opens with no styling

## What I expected to happen

# Reproducing

- Module name:
- Module version:
- Pancake version:
- Node version:
- npm version:
- Pancake settings in your `package.json`:

Steps to reproduce:

1.
2.
3.
4.

# Attachments

**Comment by alex-page** [comment]
Hi @jsephora,

I am going to close this, please feel free to open a ticket in the [uikit-starter github project](https://github.com/govau/uikit-starter).

There are issues currently, I'll try fix up my PR and get this deployed ASAP. Have a look here:
https://github.com/govau/uikit-starter/pull/9

**Comment by alex-page** [comment]
@jsephora the starterkit is all fixed up now and using the latest components. Check it out and leave any feedback in that repository 👍
