### ISSUE TITLE
Make images responsive by default.

### ISSUE THREAD

**Issue by JimBobSquarePants** [govau/uikit#321]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened

In version 1.0.0 it is required to make add the class `.au-responsive-media-img` in order to make an image responsive. 

https://gold.service.gov.au/components/responsive-media/

I would suggest making the image responsive by default and using classes to reverse that behaviour if required. 

By requiring a class integration with dynamic systems like CMS is now more difficult and since most environments will require images to be responsive it makes more sense for the default case to cater for that requirement.

**Comment by dominikwilkowski** [comment]
That’s a good point. One of our philosophies with the uikit is that we do not add any styles to anything without classes so it can be isolated and not overwrite things that already exist. 

So here is my suggestion to help with your problem:
A wrapper class `au-responsive-media` that then will apply to all children images and make them `max-width: 100%`.

Thoughts?

**Comment by JimBobSquarePants** [comment]
> So here is my suggestion to help with your problem:
A wrapper class au-responsive-media that then will apply to all children images and make them max-width: 100%.

That's definitely better but I think we can go one better still. 

How about using `.au-body img` in the same manner as you have for paragraph tags?

``` css
.au-body p {
    max-width: 42em;
    margin: 0;
}
```

This allows isolation, defines the common default and prevents any addition work from content editors.

I would go so far as doing the same for many elements headers, buttons, etc also.

**Comment by dominikwilkowski** [comment]
That’s a tricky one. the `body` component is supposed to take care of typical typography and what comes out of the usual wysiwyg CMS exports. Images and other media should be handled with something else which is what the `responsive-media` module is for. I see your point though and am inclined to add `max-width: 100%` to body but here is the rub: People tend to add the `au-body` class on everything and that will yield a lot of side effects. I think we should stay away from as much magic as we can.

To keep it clean and still give you a wrapper I think it is best to keep it in it's own wrapper class. That way we also don't need to duplicate code.

These components are so atomic that they should just do a little thing but do that well.

**Comment by JimBobSquarePants** [comment]
That's an acceptable compromise. Let's go with the `au-responsive-media` wrapper then. 👍

**Comment by alex-page** [comment]
@petrillek thanks for responding in this issue. It's safe to assume you can and should respond in closed issues to stop duplications of conversation.

We have not added `height: auto;` as it's assumed the images do not have height or width set on them. If the image is responsive it would be a bit of an anti pattern to set a height and width in HTML then tell it to respond in css. 

In some certain cases `<img src="abc.png" height="100" width="100" />` you would need to add `height: auto` and `max-width: 100%;` to make that element respond.

I do however see some potential benefit of saying "This element is responsive, make it respond" and that doesn't happen currently if a height is set.

I made a quick codepen demonstrating this: https://codepen.io/alex-page/full/geEPOM/

**Comment by dominikwilkowski** [comment]
I personally think adding a modifier for `max-height: 100%` so an image can be responsive in it's height would be an option. Adding the other respective value as `auto` won't hurt and makes the style more declarative.

**Comment by alex-page** [comment]
Making images `max-height: 100%` wouldn't be that useful as that depends on the height of the container which then would have to be set.

I am fixing up `height: auto` by default now.

**Comment by petrillek** [comment]
Nice. Thank you.
