### ISSUE TITLE
`.au-body pre code` uses tab spaces of four units, which is huge

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#325]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened
There was way too much spacing

## What I expected to happen
A logical amount of spacing

# Reproducing

- Module name: body
- Module version: lastest

Steps to reproduce:

1. wrap some code in `.au-body pre code`

# Attachments
<img width="198" alt="screen shot 2018-03-11 at 11 40 52 am" src="https://user-images.githubusercontent.com/19199063/37248248-19718c18-2521-11e8-8045-b243b4641ae1.png">

**Comment by dominikwilkowski** [comment]
I would suggest to not get into an argument about what a `logical amount of spaces` means and close this :)
[`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) can resize that space very easily and should probably be one of those user defined things. The UiKit should stay neutral and go with whatever the css default is (currently 8).

It's just one of those things that will bring a lot of passion to the discussion while solving little to no real issues. That's just my thinking though :)
