### ISSUE TITLE
AU-focus / AU-outline - non flexible when building own theme

### ISSUE THREAD

**Issue by veenarm** [govau/uikit#326]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [X] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description
## What happened
Attempted to create own 'theme' (aside from light/dark) however it's impossible in current state to re-use the AU-focus('theme') mixin because it's hard wired to $theme is either dark or  else use this color.

## What I expected to happen
Expected to be able to create my own $AU-color-theme-foreground-focus and have it used.
Seeing as there is only 1 param into these two mixins, and it only adjusts the one color, maybe the 'color' should be passed in to the mixins rather than an arbitary theme.

--
Created 4 colour vars that I wanted
Imported the sess-versioning/dist, @gov.au/core @gov.au/buttons

Added to .au-btn and a.au-btn a new theme (copied the dark one) and used my colours.

Hit the 
@include @AU-focus($theme) however theme isn't recognised and it defaults back to the primary light colour..

quick solution is obviously to overwrite the light variable in my sass file, but i'd prefer to not have to do that, patch fix would be to not use a $theme but use a $color param into the mixin.

**Comment by alex-page** [comment]
Hi @veenarm 

Thanks for submitting this issue. Our system only supports two colour options ( `light` and `dark` ). It would be extremely difficult to support the ability to add more themes.

The main pain points are:
- Classes would have to be generated based on all the different theme options
- Functional way of generating new themes that integrates them into the different classes

However our components are very flexible you are able to completely override all of the colours in the system.  We would highly recommend this approach as it will benefit from all the inbuilt accessibility checks the system does. You can do this by changing the colour values above where you import the `@import uikit.scss`.

Here is an example sass file of how this could work:
https://github.com/govau/uikit-starter/blob/dbe7e08134c2a1030eee6838b5dbd7702cadedbd/src/sass/main.scss#L2

On this line in the code you can override any of the variables in `core/sass/lib/_globals.scss` which finish with `!default`.

Here is a small example:
```
$AU-color-foreground-action: red;

// This is inside the core/sass/lib/_globals.scss, it is overrided by the above code
$AU-color-foreground-action: #00698f !default;
```
