### ISSUE TITLE
Unnecesary class in grid-12 module

### ISSUE THREAD

**Issue by petrillek** [govau/uikit#339]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

Hi. We are currently building a series of layouts for use on Government sites. The layouts will not have any classes which are specific to individual frameworks such as UI Kit or Bootstrap. We are wanting the same set of layouts to work with multiple frameworks. We are therefore looking to extend the frameworks to work with the structure provided by the layouts.

We have run into a problem when trying to extend the grids in UI Kit. We have found that extending nested selectors is generally not good idea as it will quickly blow up the CSS which is produced. Furthermore, the resulting selectors in the CSS are not the ones which are desired.

The unnecessary class is [.au-grid](https://github.com/govau/uikit/blob/master/packages/grid-12/src/sass/_module.scss#L17), which doesn’t have any styling on its own. It appears that the intention is for is to serve as a container or a namespace, however, it is not really performing this function in a useful way. It is actually causing problems as we try to extend the grid as described above.

Removing the .au-grid selector from the SASS makes extends possible and has no bad knock on effects as far as we can see. We would like the selector to be removed so that the rules become simpler and we can extend the way we would like. 

https://github.com/govau/uikit/blob/master/packages/grid-12/src/sass/_module.scss#L17
Can the .au-grid selector be removed from the SASS file above?

## What happened
``` CSS
.header-section .header {
 @extend .col-sm-12;
}
```
will produce 
``` CSS
.au-grid .col-sm-12, .au-grid .header-section .header, .header-section .au-grid .header {
    width: 100%; }
```
Note the mixed order of the selectors.

## What I expected to happen
If we remove the .au-grid the result will be much neater:
``` CSS
.col-sm-12, .header-section .header {
    width: 100%; }
```

# Reproducing

- Module name: grid-12
- Module version: 2.0.1
- Pancake version: 1.1.0

**Comment by alex-page** [comment]
Hi @petrillek thanks for the detailed issue 👍 

What i'm seeing is the expected outcome of extending this class in sass. Is there any particular reason you can't add `au-grid` to a parent html element then use the `col-sm-12` class?

The `au-grid` class is added for specificity. If a developer or designer is using another grid system which uses the same classes or has an element with the class of `.container` it means they do not inherit those styles. This was a fundamental decision we made when creating this design system as we didn't want styles to leak onto elements unintentionally.

We are trying to keep our grid system as simple as possible, doing this meant we wanted it to feel and act like bootstrap as it's most familiar to our users. An option which I am not too fond of would be prefixing the grid classes with `au-` for example `au-container`. This option would potentially remove the relationship with bootstrap and would require a community decision to be made.

We will also add some rationale explaining this decision on our documentation website https://github.com/govau/designsystem/issues/86

**Comment by alex-page** [comment]
Additional rationale has now been added:
https://designsystem.gov.au/components/grid-12/rationale/
