### ISSUE TITLE
Using `FooterEnd` component it wraps content in `<nav>`

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#342]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

## What happened

I used the `FooterEnd` react component to get the nice spacing and border top. However when used it wrapped my content inside a html5 navigation element. This was not desired as we wanted to put a paragraph inside this component.

## What I expected to happen

I expected that `FooterEnd` would output a `div` and if a user was going to add a navigation inside it they could add their own markup.

# Reproducing

- Module name: footer
- Module version: 2.0.1

Steps to reproduce:

1. Use `FooterNav`
2. Put some content inside that is not navigation
3. It will be wrapped inside a `<nav>`

**Comment by pattyde** [comment]
Fixed by https://github.com/govau/uikit/pull/383
