### ISSUE TITLE
Minor duplication of selector & property in Sass source in Responsive media module

### ISSUE THREAD

**Issue by klepas** [govau/uikit#346]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# Description

Minor duplication of selector rule and property in the _Responsive media_ module; no impact on CSS output, but duplicate in source. (:

## What happened

Compare:

1. https://github.com/govau/uikit/blob/develop/packages/responsive-media/src/sass/_module.scss#L25
2. https://github.com/govau/uikit/blob/develop/packages/responsive-media/src/sass/_module.scss#L46

## What I expected to happen

Only one source rule.

**Comment by alex-page** [comment]
Nice find @klepas i'll fix that one up right now.
