### ISSUE TITLE
Accordion delays on Android

### ISSUE THREAD

**Issue by roflcopterDorrie** [govau/uikit#357]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

When using UIKit.accordion to open and close a menu, there is a delay before the animation starts on Android devices.

# What I expected to happen

The animation to start immediately.

# Reproducing

- Module name: Accordion
- Module version: v0.3 (although I couldn't see any differences between v0.3 and v2.0 besides the namespace, so most likely affecting the latest version as well)
- Pancake version: v1.1.0
- Node version: v9.10.1
- npm version: v5.6
- Pancake settings in your `package.json`:
```
"pancake": {
    "auto-save": true,
    "plugins": true,
    "ignore": [],
    "css": {
      "minified": true,
      "modules": false,
      "browsers": [
        "last 2 versions",
        "ie 8",
        "ie 9",
        "ie 10"
      ],
      "location": "css/",
      "name": false
    },
    "sass": {
      "modules": false,
      "location": "sass/vendors/",
      "name": "uikit.scss"
    },
    "js": {
      "minified": false,
      "modules": false,
      "location": "pancake/js/",
      "name": "pancake.js"
    },
    "react": {
      "location": "pancake/react/"
    }
  }
```
 - Device: Google Pixel - Android v8.1.0
 - Browser: Chrome v66.0.3359.126

Steps to reproduce:

1. Load the the attached site on an android device using chrome
2. Click the open menu
3. Click the close menu
4. Scroll to the bottom of the page
5. Scroll to the top of the page
6. Click the open menu
7. There will be a delay before the animation starts.

I have tried to isolate the issue as best I can, narrowing it down to some javascript in the Drupal module Google Analytics, part of the GovCMS distribution. 

Specifically this code in /test_files/googleanalytics.js
```
$(document.body).bind("mousedown keyup touchstart", function(event) {
});
```
When this code is removed, the delay seems to disappear.

I have also tried swapping out UIKit accordion for jQuery.animate as a test and found there is no delay using jQuery animate.

This also seems to be much more significant when there is a lot of markup on the page. If there isn't much markup, the delay is not noticeable.

I would just remove the offending code but its part of core GovCMS, so that isn't an option.

# Attachments
[accordion-android-lag.zip](https://github.com/govau/uikit/files/1959545/accordion-android-lag.zip)
https://www.youtube.com/watch?v=zkYPHgzb54Y

**Comment by alex-page** [comment]
@roflcopterDorrie Thanks for the detailed issue!

I can't replicate this issue on my Samsung s7, I will see what we can do to get our hands on a google pixel!

More than likely it is an issue with GovCMS as the code comes from their platform and our code is system agnostic.

**Comment by roflcopterDorrie** [comment]
@alex-page I can confirm that there isn't any delay on https://uikit.service.gov.au/packages/accordion/tests/site/ on my pixel.

**Comment by alex-page** [comment]
Hey @roflcopterDorrie that makes it quite hard for us to fix unfortunately as the component was built to be system agnostic.

Can you make an issue with the Drupal analytics module, I am keen to hear what the result is of this.

**Comment by alex-page** [comment]
Thanks @roflcopterDorrie I'll see what I can dig up with your example 😄

**Comment by alex-page** [comment]
I am really not sure what is causing this issue. The exact same code is being run on the [designsystem.gov.au](https://designsystem.gov.au) header bar and isn't having any trouble pushing all the content down.

I also recorded a browserstack google pixel with frame rate, gpu memory and paint complexity on. You can see an obvious spike in memory and decrease in fps when the accordion is open/closed. You can also see that all of the content below the accordion needs to be repainted. This can cause issues with performance I would love to know if using other accordions such as[ jQuery UI accordion](https://jqueryui.com/accordion/) have the same problems as this one.

It seems that multiple touch events are being fired at once. The event listener for `touchstart` that logs to the console and the function `toggleAccordion` are ran at the same time. Some ideas that may help are:
- Stop the bubbling of events, run one touch event at a time: https://javascript.info/bubbling-and-capturing
- Try to have less content below an accordion ( I know this is a pretty lame, however the more elements that need to be redrawn the greater the paint complexity will be )

Things we are going to do:
- Add some rationale on best practices for implementing the accordion
- Experiment to see if `will-change` css property optimises the accordion animation

Here is the recording mentioned above:
![accordion-pixel](https://user-images.githubusercontent.com/19199063/39683124-23f77974-51f7-11e8-9188-72b2f6af9ee1.gif)

**Comment by roflcopterDorrie** [comment]
@alex-page just to add another complexity to this, the original reason I opened this issue is that I am finding an additional delay that I get when I have scrolled to the bottom of the page and then scrolled back up. 

To replicate:
- Scroll to the bottom of the screen
- Scroll to the top of the screen
- Click the accordion title, there is a delay of a second or so before the animation starts
This only seems to happen when you scroll to the bottom and back up again... not sure why

Anyway, good luck :)

**Comment by alex-page** [comment]
@roflcopterDorrie I did a bunch of research on this.

This is due to the way the accordion animates and the content below it moves. If we look at [CSS triggers](https://csstriggers.com/) you can tell what events happen in the browser.

The accordion changes `height` on the `.au-accordion__body` which causes issues with:
- Alters geometry of element which causes alterations to other elements on the page
- Painted and composited, which means pixels are actually rendered on change

One option that comes to mind is moving to rotate. We could move the body content of the accordion on the 3d plane and reduce issues with performance. Also we could add the `will-change` property which initialises the GPU and lets it know the element will be changing.

It will not be possible for our team to solve the content moving underneath. This component can not change the content underneath it. This means that pages with lots of content below an accordion will always have to perform repaint and geometry alterations.

**Comment by pattyde** [comment]
Have had to move this to the upcoming sprint (starting tomorrow) as we weren't able to do it this sprint.

**Comment by alex-page** [comment]
@roflcopterDorrie sorry for the late reply. This issue is going to require a fair chunk of work to the animate component. 

I am not sure how much value reworking the animate module would have as the page will repaint as the accordion size changes which is the original cause of the jank.

We are not able to smoothly animate the content below the accordion as that would require wrapping it in an element and moving it with the GPU instead of repainting the elements.

Let me know what you think, I may have to close this or do some experimentation into how much benefit/work would be required to do the animation with `transform`

**Comment by roflcopterDorrie** [comment]
So I have just done some more testing using Chrome 71 on my Google Pixel (the phone I had the issue with initially) and I cannot replicate the delay issue anymore.
There is still some performance issues, but to be honest as long as there is something happening on the screen, I think users will be okay with this. What I was worried about was a user clicking the expand and nothing happening, which I believe has been resolved by Chrome.

Just FYI, this is a great example of the performance issue in practice:
https://immunisationhandbook.govcms.gov.au/vaccine-preventable-diseases/meningococcal-disease
Click expand all and watch it crawl to a halt :)
I am not sure that jQuery would do a better job, it is a lot of markup to move around and I think any phone would struggle.

So I think we can safely close this issue for now 👍
