### ISSUE TITLE
Main Navigation Component Draft

### ISSUE THREAD

**Issue by TrebBrennan** [govau/uikit#359]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Community discussion around the the need for a _main_ navigation component has evolved to a point where it can be considered for inclusion in the Design System.

Provide draft code for discussion.

**Comment by pattyde** [comment]
Progressing work with the main navigation component, discussion ongoing here. 

https://community.digital.gov.au/t/navigation-main-horizontal/251/11
