### ISSUE TITLE
Discovery on tech/deployment solution for templates

### ISSUE THREAD

**Issue by TrebBrennan** [govau/uikit#360]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Templates are likely to require a deployment pipeline. Reach a clear understanding of how we are going to distribute templates to our users.

**Comment by pattyde** [comment]
Discussion notes

Design system website needs:
  - List of templates
  - Ability to download individual templates
  - View template in browser/simple interactions e.g. menus, hover, focus


Individual templates need to:
  - Accessibility tested
  - Browser and device tested
  - Use the default uikit colours
  - Version controlled with semantic versioning
  - Use latest at time of download components ???
  - Contain no-js
  - Works without js
  - Print styles
  - Helps to guide customisation
  - Similar folder structure to furnace zip
  - Try and use the furnace API for css/sass/js/react ??


What is in the downloaded file:
  - html
  - assets
    - images
    - favicon
    - css
    - js
  - <head> properties
  - best practice js and css performance
  - build processes
  - react ???


MVP:
  - Design a template listing page that allows preview ( screen capture ) download
  - Develop template listing page
  - Template - tested like our components
  - Template - no-js/print styles
  - Template - browser and devices
  - Community thread and one thread page per template
  - Download a zip file that contains:
    - HTML, CSS, JS, assets ( images, favicon )
    - Some basic guidance on customisation
    - Latest versions of components
  - Discovery in how component versions flow into template versions
  - Templates versioned individually with semantic versioning


Extras:
  - Design template preview page
  - Develop template preview page
  - Rationale/Accessibility for templates
  - Build processes for SASS -> CSS and JS -> minified/concat
  - React templates
