### ISSUE TITLE
Image / Asset pipeline for components

### ISSUE THREAD

**Issue by TrebBrennan** [govau/uikit#361]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

In order to work on whole of government header templates we will need to resolve how images/assets are distributed to components in the Design System (for the Coat of Arms)

**Comment by alex-page** [comment]
I'm going to close this one. We currently have a use case for one image in one component. I don't think this needs a pipeline.
