### ISSUE TITLE
Request: OpenWithoutAnimation() and CloseWithoutAnimation() public methods on Accordion

### ISSUE THREAD

**Issue by sirleech** [govau/uikit#363]
Requesting some new methods on AU.Accordion that give me control of the open/close without the animation. Use case is for mobile viewports where accordions might be closed by default to save space. The same accordion is expanded on large viewports where there is more space.

- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

**Comment by alex-page** [comment]
@sirleech I am going to close this. Currently users can set the speed of the animation, this allows them to set it to `0`.

If there are any issues with this implementation let me know 👍

**Comment by sirleech** [comment]
Thanks @alex-page -- setting speed="1" seems to work, however I got an error setting it to "0". All good --- using speed="1" was the functionality I was looking for.
