### ISSUE TITLE
Multi line text with radio buttons and checkboxes has tight lineheight

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#364]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Added a whole bunch of content to a radio button or checkbox. There was lots of incorrect line height and spacing, making the element hard to read.

# What I expected to happen

Consistent alignment and spacing, regardless of how much content is inside the checkbox or radio button.

# Reproducing

- Module name: control-input
- Module version: 2.0.2

# Attachments
<img width="645" alt="screen shot 2018-05-09 at 10 34 56 am" src="https://user-images.githubusercontent.com/19199063/39789772-50f33ea2-5375-11e8-8dcf-66e39a1361fd.png">

**Comment by pattyde** [comment]
https://github.com/govau/uikit/pull/391
