### ISSUE TITLE
Give au-footer--dark the same text styles as au-body--dark

### ISSUE THREAD

**Issue by AlexGilleran** [govau/uikit#366]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened
If you have a normal au-body but a footer that uses au-footer--dark, links on the footer (my use case in particular is using au-link-list) inherit styles that assume a light background.
![image](https://user-images.githubusercontent.com/900555/39857894-48453a72-5478-11e8-84e3-48e7027f8453.png)

# What I ~expected to happen~ would like to happen
It'd be good if children of an au-footer--dark element got the same styles as if they were under au-body--dark, so they look good on the dark background.

![image](https://user-images.githubusercontent.com/900555/39857952-71422494-5478-11e8-9897-ce393d3d435e.png)

Or potentially if there was just some way to override the light styles individually?

# Reproducing

- Module name: Body / Footer / Link List
- Module version: 2.0.2 / 2.0.1 / 2.0.1
- Pancake version: 1.2.0
- Node version: 8
- ~npm~ yarn version: 1.6.0
- Pancake settings in your `package.json`:
```
{
    "auto-save": true,
    "plugins": true,
    "ignore": [],
    "json": {
      "enable": true,
      "location": "pancake/",
      "name": "pancake",
      "content": {
        "name": true,
        "version": true,
        "dependencies": true,
        "path": true,
        "settings": true
      }
    },
    "css": {
      "minified": true,
      "modules": false,
      "browsers": [
        "last 2 versions",
        "ie 8",
        "ie 9",
        "ie 10"
      ],
      "location": "pancake/css/",
      "name": false
    },
    "sass": {
      "modules": true,
      "location": "pancake/sass/",
      "name": "pancake.scss"
    },
    "react": {
      "location": "pancake/react/"
    }
  }
```

Steps to reproduce:

1. Create a page with class `au-body` but no `au-body--dark`
2. Put an element with `au-footer au-footer--dark` under it
3. Put an `<a>` under that.

**Comment by TrebBrennan** [comment]
Hi Alex.
`au-footer au-footer--dark au-body au-body--dark` on your footer will fix this for you.

`.au-body` is intended for an area where you want [default content/type styles](https://designsystem.gov.au/components/body/) so it's probably best not to have it leaking out everywhere from a top level parent like `<body>` or something anyway. I would recommend adding it only to areas when you find that you need it.

I hope that helps. Let me know how you go. :)

**Note.** I see this as a failure in our documentation not your implementation. I've just added a docs label and we'll look at rectifying this in the docs. Unless someone else wants to have a go ;) [body docs](https://github.com/govau/designsystem/tree/master/content/components/body), [footer docs](https://github.com/govau/designsystem/tree/master/content/components/footer)

**Comment by AlexGilleran** [comment]
Oh right, easy peasy then, thanks @TrebBrennan :)
