### ISSUE TITLE
Accordion: html component open by default, and react closed by default

### ISSUE THREAD

**Issue by sirleech** [govau/uikit#368]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

I've consumed the uikit accordion in a fresh create-react-app. When using the code example from the design system documentation, I get an accordion that is closed (indicated by carat down). However the accordion body is showing. 

When you click the accordion, the behaviour seems to reset and it is fine from then.

# What I expected to happen

I would expect the accordion to be closed by default with body hidden.

# Reproducing

- Module name: Accordion
- Module version: 2.0.1
- Pancake version:  ?
- Node version: 9.9.0
- npm version: 6.0.1
- Pancake settings in your `package.json`:

`  "pancake": {
    "auto-save": true,
    "plugins": true,
    "ignore": [],
    "json": {
      "enable": false,
      "location": "pancake/",
      "name": "pancake",
      "content": {
        "name": true,
        "version": true,
        "dependencies": true,
        "path": true,
        "settings": true
      }
    },`

# Steps to reproduce:

A sample app can be found here:
https://github.com/sirleech/govau-uikit-test
`npm start`

# Attachments

![image](https://user-images.githubusercontent.com/680844/39972449-6b1d4732-5753-11e8-94c5-7ce27a667172.png)

**Comment by sirleech** [comment]
Thanks Pagey-- as discussed, adding the `class="js"` into the HTML tag works. 

`<html lang="en" class="js">`

**Comment by alex-page** [comment]
For anyone seeing this issue in the future adding the `class="js"` is not the solution. Best practice is to have a `<html class="no-js">` then run a little bit of javascript to remove `no-js` and replace it with `js`.

Here is an example snippet:
```
// Remove no-js
var $html=document.documentElement;if($html.classList)$html.classList.remove("no-js"),$html.classList.add("js");else{var className="no-js";$html.className=$html.className.replace(new RegExp("(^|\\b)"+className.split(" ").join("|")+"(\\b|$)","gi")," "),$html.className+=" js"}
```

**Comment by alex-page** [comment]
This is also related to https://github.com/govau/designsystem/issues/63
