### ISSUE TITLE
new module: logos

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#37]
Stuff to cater for logo marks (images) and logo text, something akin to what we have in the design guide inner header.

**Comment by elisechant** [comment]
do you intend to have logos as resource downloads or supply them as CDN paths?

**Comment by dominikwilkowski** [comment]
As far as I know we have no CDN so we will give you the assets with npm. I will try to keep pixel graphics out of it as much as I can. So far I know only of one. The rest will be SVGs

**Comment by klepas** [comment]
In my mind I see this module more as *providing support for custom logos*, than logos themselves — @elisechant @dominikwilkowski or am I off the mark here?

**Comment by elisechant** [comment]
@klepas no I think you are probably right as well. I suppose that some logos will be consistent like the Commonwealth of Aus Logo, but you're right maybe those sort of resources should be downloaded elsewhere.

**Comment by dominikwilkowski** [comment]
I also like the idea of just creating a module for SVGs in general that gives you a place to put them and a way to use them. Pixel graphics should be downloaded as zips (to prevent hot linking) from the site.

**Comment by joahua** [comment]
@TrebBrennan has mentioned work done on improving the Commonwealth logo SVG - definitely some value in providing canonical versions of this. Some work has also been done on small screen readability.
