### ISSUE TITLE
Replace npm with yarn

### ISSUE THREAD

**Issue by adamzerella** [govau/uikit#381]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened
Yarn is a `superior` package manager yet there is no easy build option to **copy** on the download page. 😞 

# Attachments
<img width="271" alt="screen shot 2018-05-15 at 10 42 08 am" src="https://user-images.githubusercontent.com/1501560/40030263-ed1a86bc-582c-11e8-8852-1a44ab383d3b.png">

**Comment by alex-page** [comment]
Most experienced users of superior package managers would know that they can replace `npm install` with `yarn add` 😂 

I think this is valid request however all of our `README.md` files and component pages currently are documented using `npm`. I would like to see this be a broader change of replacing `npm` with `yarn` however I feel like this is a bit of a lower priority as users can replace `npm install` with `yarn add`.

**Comment by pattyde** [comment]
A bit late to the party, but I agree with @alex-page: this change would definitely have value but it's not a high priority for us right now. 

That said, this would be a great first issue for new contributors so if anyone is interested in starting this issue, let us know! :)

**Comment by alex-page** [comment]
I am going to close this repository, a lot has happened in the past few months and `npm` is doing just fine.

When we move over to `bolt` we can use `npm` because `bolt` uses the `npm` ecosystem.
