### ISSUE TITLE
Invalid state doesn't work in IE9 and IE8

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#384]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Opened the test page in IE8 and IE9 could not see the invalid state.

# What I expected to happen

See invalid state in older browsers.

# Reproducing

- Module name: control-input
- Module version: v2.0.3

# Attachments
<img width="310" alt="screen shot 2018-05-15 at 5 00 29 pm" src="https://user-images.githubusercontent.com/19199063/40041495-7fb2dbd0-5861-11e8-8cd5-5482f5c23d17.png">

**Comment by pattyde** [comment]
Fixed by https://github.com/govau/uikit/pull/391

Tested in IE9 and IE8 on Windows 7
