### ISSUE TITLE
Skip links to do not move focus

### ISSUE THREAD

**Issue by imperator99** [govau/uikit#389]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Skip links do not move focus in Chrome. Tabbing onto a skip link and then pressing enter moves the viewport to the correct location, but subsequent tabs show the focus does not actually move.

For example, tabbing onto 'Skip to main content' and then pressing 'Enter' will move the viewport to the top of the main content, but then a second tab will cause the 'Skip to navigation' link to receive focus.

Destination anchors need a `tabindex` of `-1` for the focus to move properly.

I suggest the documentation be updated to include this information.

# What I expected to happen

When using a skip link, the keyboard focus should move along with the visual focus.

**Comment by mgdhs** [comment]
This is a funny one which runs into old school web. It definitely behaves differently in various browsers. 

The _destination_ needs to be an anchor to capture focus: `<a id="#content"></a>`. This means the UITK may need to pick a different ID so it won't clash.

**Comment by alex-page** [comment]
Thanks @imperator99 there should now be more detailed documentation around this.
