### ISSUE TITLE
Interactive components should be able to use `Link` component from react router

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#390]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Developers using react router have to do a work around to modify the `this.props.history` whenever using an interactive link.

This was brought up by @rooby in the community:
https://community.digital.gov.au/t/recommendations-best-practices-for-using-components-with-react-router/275/2

Steps to reproduce:

1. Install link-list
2. Add react router
3. Change the history without using the Link component

# What I expected to happen

We should give developers flexibility to use whatever component they want for interactive elements.

**Comment by rooby** [comment]
Do you know what the timeline is on this one?

Do you have a specific approach in mind? If so I can submit a PR if that would be of use.

**Comment by alex-page** [comment]
I was going to work on this and get it done by next wednesday. It's a pretty simple approach just time consuming and needs to be applied and documented for all interactive components.

If you want to do it, I can give you much more detailed information 👍
