### ISSUE TITLE
aria-controls has invalid attribute reference

### ISSUE THREAD

**Issue by HerinHentry** [govau/uikit#396]
https://designsystem.gov.au/components/animate/

Invalid attribute reference : aria-controls="close" etc.

**Comment by TrebBrennan** [comment]
Hi @HerinHentry thanks for the issue.

It's not super clear what you're referring to. But after a quick look I'm guessing you're referencing the animate example code `aria-controls="close"` which doesn't seem to reference an actual element in the example?

I think in that example the correct attribute would be: `aria-controls="dropdown-1"`

Did i get this right?

**Comment by HerinHentry** [comment]
Yup... dropdown-1 it is!

It's easier to run the aXe tool on each page to check if it conforms to ARIA specifications. I have got the Chrome plug-in for aXe installed. Lifesaver for sure!

**Comment by electronicwoft** [comment]
Hi team, 
In my view, there are several accessibility issues outstanding with the animation widget, and, while automation might be useful for highlighting problems with implementation, it's not much use for determining what is accessible. It is not possible to programmatically determine the current state of this widget (i.e., whether the animated element is visible). Also, the aria-controls attribute on each control (open, close, toggle) also may point to content that may not be either visible or focusable. Using this widget with a screen reader will likely require unnecessary exploration to determine whether anything has taken place when any of the buttons are activated. this could be resolved if there was one button whose accessible name toggled in line with the visibility of the animated content and aria-controls was only present when the content was visible.
