### ISSUE TITLE
Body - Horizontal Separator Bar

### ISSUE THREAD

**Issue by HerinHentry** [govau/uikit#406]
Regarding Body https://designsystem.gov.au/components/body/

The horizontal separator bar <hr> used as a separator for visual separation. This can be hidden from screen readers using aria-hidden="true".

When there is only one separator, this is fine. But, if people use multiple separators inside a page without thinking about the impact on the screen reader, this can be annoying to hear [horizontal splitter] multiple times.

**Comment by alex-page** [comment]
@HerinHentry Great pickup seems like a simple bit of documentation for the rationale page 👍

**Comment by alex-page** [comment]
The documentation has been updated for the horizontal rule. Thanks @HerinHentry, feel free to re open this if you have any concerns.
