### ISSUE TITLE
Breadcrumb - focus and aria-current

### ISSUE THREAD

**Issue by HerinHentry** [govau/uikit#407]
Regarding Breadcrumb https://designsystem.gov.au/components/breadcrumbs/live/

The last list item needs to be keyboard focusable and use aria-current for screen reader users identify the location.

An example can be seen here
https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html

**Comment by gordongrace** [comment]
From: https://www.w3.org/TR/wai-aria-practices/#breadcrumb

> The link to the current page has aria-current set to page. If the element representing the current page is not a link, aria-current is optional.

Linked and non-linked variants of the last item in the breadcrumb both appear to be supported/endorsed. Perhaps the examples should add a linked last item variant, and include the `aria-current` attribute?

Also discussed at:
https://community.digital.gov.au/t/breadcrumbs/72/3

**Comment by HerinHentry** [comment]
In the current example, If we listen to the screen reader, it announces 

breadcrumb navigation landmark 
list with 3 items
Home link
Parent link
out of list

This is a discrepancy between screen readers using form and browse mode. IMO, it's better to be a link to maintain consistency.

**Comment by alex-page** [comment]
I'm happy to discuss this one further I can see benefits on both sides thanks @gordongrace and @HerinHentry

**Comment by alex-page** [comment]
For this ticket we need to do some experimentation with active links.

We need to test links in lists with different screen readers and compare the differences when using `aria-current` on a link versus no link.

We then need to share the results.

**Comment by sukhrajghuman** [comment]
Adding link on last item of breadcrumbs and adding `aria-current="page"`.

```html
        <li>
            <a href="#" aria-current="page">Banana</a>
        </li>
```
Using VoiceOver and  Safari, I get the following reading:

> "Current page, link, Banana"

Using ChromeVox on Chrome:

> "Banana, Link list item"

I will have access to a windows device tomorrow, so I will test it using NVDA.

**Comment by sukhrajghuman** [comment]
Thanks for bringing this up @HerinHentry.

Based on our research, both approaches are valid. For now, we will keep the last item on breadcrumbs without a link. The reasoning for this is that not all [browser/screenreader](http://design-patterns.tink.uk/aria-current/) combinations are yet to support `aria-current="page"`. 

It is useful to have current page being read out on the final item of the breadcrumbs list, but it is also useful being told that the last item is not a link as the user is already on this page. We are trying our best to balance these two approaches.

We will add additional rationale to the breadcrumbs page explaining the two approaches and how they are read by a screen reader.

**Comment by sukhrajghuman** [comment]
@HerinHentry we have [added some rationale](https://designsystem.gov.au/components/breadcrumbs/rationale/) on the documentation website regarding this. Thanks once again for bringing this up. We really value your input 🙂

**Comment by alex-page** [comment]
@HerinHentry let me know if you or your team would like to go on the Design System website as contributor/s. There are a few components you have had some invaluable feedback on and I want to make sure you are credited for that work.
