### ISSUE TITLE
Page alerts - Prefix text

### ISSUE THREAD

**Issue by HerinHentry** [govau/uikit#412]
Regarding Page alert: 
I like the documentation to differentiate this. 

**From Rationale**
Alert title We can't simply rely on icons and colour to convey meaning, so an alert title should always accompany the alert text.

But, I think it would add value if the alert can be prefixed by
"Success", "Info" etc. This is one way of differentiating the alerts when the icons are lost as per #403.

Maybe an enhancement. Good job on the progress indicator prefixes. They are fantastic!

**Comment by alex-page** [comment]
Thanks @HerinHentry great feedback again!

**Comment by alex-page** [comment]
We have updated the titles on the documentation website and the rationale. Feel free to re open this ticket if you have any concerns. Thanks @HerinHentry
