### ISSUE TITLE
Progress indicator - Active / Inactive states

### ISSUE THREAD

**Issue by HerinHentry** [govau/uikit#413]
Regarding Progress Indicator - https://designsystem.gov.au/components/progress-indicator/

With progress indicator, when we are using in websites or web applications, this is also used to indicate a state which is active for admins and disabled for users.
The very common example is forms progress indicator which has stage 2 disabled until stage 1 is complete.

Can we please include an example of disabled/informative progress indicator as well?

**Comment by TrebBrennan** [comment]
Thanks @HerinHentry. I've added this suggestion to the community discussion for this component
https://community.digital.gov.au/t/progress-indicator/86
