### ISSUE TITLE
Link list component doesn't seem to support object types for list items

### ISSUE THREAD

**Issue by adamzerella** [govau/uikit#425]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened
![image](https://user-images.githubusercontent.com/1501560/41629290-0b09cc9a-746c-11e8-9ea5-62add1ff7949.png)

# What I expected to happen
To be able to use a certain `Link` object as the `linkComponent` 

Link list component works great when setting the linkComponent for the entire list, just not unique list items.

# Reproducing

- Module name: `link-list`
- Module version: `2.1.1`
- Pancake version: `1.2.3`
- Node version: `8.11.1`
- npm version: `5.6.0`
- Pancake settings in your `package.json`: NA

Steps to reproduce:

```
import { Link } from 'react-router-dom'

<AUlinkList
items = {
	[{
		link: "/about",
		text: "About",
		linkComponent: {
			Link
		}
	}]
}
/>
```

**Comment by alex-page** [comment]
@adamzerella Thanks for bringing this up. It seems you were caught out by `JSX`.

In one instance when you set a property you would do `LinkComponent={ Link }` in this instance you are setting a value on an object `Linkcomponent: Link`.

If this is brought up again we can look into better documentation or an alternative solutions.
