### ISSUE TITLE
Get SSL cert for http://guides.service.gov.au/design-guide/

### ISSUE THREAD

**Issue by joahua** [govau/uikit#43]
It seems we already have a (working) wildcard cert for *.service.gov.au - do we need something more specific for guides @dominikwilkowski?

![image](https://cloud.githubusercontent.com/assets/499804/22187723/7a70b3ec-e15f-11e6-94f2-fe352c5fb315.png)

**Comment by joahua** [comment]
It seems we already have a (working) wildcard cert for *.service.gov.au - do we need something more specific for guides @dominikwilkowski?

![image](https://cloud.githubusercontent.com/assets/499804/22187723/7a70b3ec-e15f-11e6-94f2-fe352c5fb315.png)

**Comment by dominikwilkowski** [comment]
Just checked. I guess the only thing we need now is a 301 from http -> https

**Comment by joahua** [comment]
I'll raise another issue to track that :)
