### ISSUE TITLE
Circle CI build fails as it's finding a lib folder in a non existent directory

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#452]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened
Circle CI build failed due to:
```
find: `./packages/tags/node_modules/sockjs-client/lib/transport/lib': No such file or directory
```

# What I expected to happen
Build doesn't fail due to `node_modules` in the component folder.

# Attachments
<img width="712" alt="screen shot 2018-07-24 at 2 00 04 pm" src="https://user-images.githubusercontent.com/19199063/43116205-e27386ce-8f49-11e8-8f8d-e5c2fccb084b.png">

**Comment by adamzerella** [comment]
@alex-page I believe this has been resolved with the recent improvements to the CI build from: https://github.com/govau/uikit/pull/441

**Comment by alex-page** [comment]
Thanks @adamzerella legend
