### ISSUE TITLE
Add issue template similar to babel

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/uikit#455]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

**Comment by pattyde** [comment]
Hi @sukhrajghuman,

Can you provide a bit more details about what improvements you'd like to see with the issue template, and why you think they'd be beneficial?

What do you think is missing from our current issue template?

What additions would improve the issue template to help folks creating new issues, or making feature requests?

Is this based on your experiences, or are you suggesting this on behalf of folks from the community?

All this info will help us determine the scope of the issue and prioritise when we'll be able to work on it.

**Comment by alex-page** [comment]
I suggested this one @pattyde it has huge benefits check out this page:
https://github.com/babel/babel/issues/new/choose
