### ISSUE TITLE
Print stylesheet: Links inconsistent (internal vs external)

### ISSUE THREAD

**Issue by sirleech** [govau/uikit#457]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

While implementing print stylesheets on our website using UIKit, I noticed internal and external links are not styled consistently.

Looks like this code here:
https://github.com/govau/uikit/blob/8d75ec16375ba1ca9c21dfa6426fbd8697f0245c/packages/body/src/sass/_print.scss

# What I expected to happen

I expect the links to style consistently. For example, internal links display the URL after the link, as well as external links. Currently internals display URL, but not the externals (rel=external).

# Reproducing

- Module name: body
- Module version: latest
- Pancake version: latest
- Node version:
- npm version:
- Pancake settings in your `package.json`:

Steps to reproduce:

1. Print out a page that uses internal and external links.

**Comment by alex-page** [comment]
Thanks @sirleech i'll try get @sukhrajghuman to have a look at this in the coming sprint.

**Comment by sirleech** [comment]
Nice!!!
