### ISSUE TITLE
npm run bootstrap is removing the contents of readme.md

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#499]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Running `npm run bootstrap` is deleting all of the contents inside the `readme.md` file.

## What I expected to happen

`npm run bootstrap` should generate some things in the file without destroying its contents.

Steps to reproduce:

1. Run `npm run bootstrap` after `npm run bootstrap` has ran on a clean install

**Comment by sukhrajghuman** [comment]
This is happening when running `npm run bootstrap` after updating a component version. Will look into it more

**Comment by sukhrajghuman** [comment]
Okay I can't seem to recreate it anymore:

I've tried the following:

### option 1

1. `npm run nuke`
2. `npm i`
3. `npm run bootstrap`
4. Update npm version of any package
5. `npm run bootstrap`

### option 2

1. `npm run nuke`
2. `npm i`
3. Update npm version of any package 
4. `npm run bootstrap`

### option 3

1. `npm run nuke`
2. `npm i`
3. `npm run scaffolding`
4. `npm run bootstrap`

**Comment by alex-page** [comment]
@sukhrajghuman and @adamzerella have you noticed this recently 😬

**Comment by adamzerella** [comment]
@alex-page I'm unable to replicated this using the steps outlined.

**Comment by alex-page** [comment]
I am going to close this issue, if @sukhrajghuman or @adamzerella or myself notice the readme getting removed we will reopen this issue.
