### ISSUE TITLE
Callout has margin bottom

### ISSUE THREAD

**Issue by roflcopterDorrie** [govau/uikit#506]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

au-callout has a margin-bottom
My understanding is that the components have margin-top only (could be wrong)

## What I expected to happen

That the space between au-callout and the next element is controlled by the next element

## Reproducing

- Module name: au-callout
- Module version: 2.0.7
- Pancake version: 1.2.4
- Node version: 9.10.1
- npm version: 6.4.0

Steps to reproduce:

1. Go to https://designsystem.gov.au/components/callout/
2. Inspect the calendar callout

## Attachments
Line 25 of https://github.com/govau/uikit/blob/master/packages/callout/src/sass/_module.scss
<img width="933" alt="screen shot 2018-09-06 at 4 39 22 pm" src="https://user-images.githubusercontent.com/11580046/45139570-8452fa80-b1f3-11e8-8c1d-3749808f9874.png">

**Comment by alex-page** [comment]
Thanks @roflcopterDorrie from memory there are some components we felt always needed an additional nudge. I might investigate this and write some tests to see if we can remove this code. 

Thanks for letting us now 👍

**Comment by roflcopterDorrie** [comment]
Yep that makes sense, the need for a bigger margin leading up to the callout.
For me I think the main thing is that if nothing followed the callout, there would be a bottom margin.
So maybe option 3 might work the best?

**Comment by alex-page** [comment]
Yeah that is my gut feeling as well. I'll get this implemented this sprint in a minor version.

**Comment by alex-page** [comment]
@roflcopterDorrie this has been resolved in version `2.1.0`. Let me know if you have any feedback!
