### ISSUE TITLE
Accordion broken when downloading from furnace

### ISSUE THREAD

**Issue by BrendanCNg** [govau/uikit#512]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
The Accordion is 'expanded' on page load and is unresponsive to clicks to 'minimise' and 'expand' 

## What I expected to happen
The accordion to be minimised when loaded and respond to minimise and expand when clicking
 

## Reproducing

- Module name: Accordion
- Module version: 5.0.2

Steps to reproduce:

1. Download Accordion and dependencies (Core, Accordion, Animate) as CSS minified and Javascript minified. from the [designsystems download page](https://designsystem.gov.au/download/)
2. Create index.html
3. Reference the CSS and Javascript in index.html
4. Open index.html in browser

## Attachments
![image](https://user-images.githubusercontent.com/36283933/45341414-f2296880-b5dd-11e8-9ad5-eb976345f50f.png)

**Comment by alex-page** [comment]
Thanks @BrendanCNg we require a lot more documentation for a page template there is required code that would be missing here. Have a look at this issue https://github.com/govau/uikit/pull/505 and see if the discussion in it can help solve your problem.

**Comment by BrendanCNg** [comment]
oh my bad I needed to add this script to the head.

https://github.com/govau/uikit/blob/f69d6e71ca41c7159914d4cbaf8e60764c909c3b/packages/accordion/tests/site/index.html#L21-L23

Thanks alot. 👍

**Comment by alex-page** [comment]
I will make sure this is documented soon, thanks for your patience!
