### ISSUE TITLE
Accordion state doesn't update when clicking accordion title then state toggle

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#516]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

@ndavison brought this up what a legend! When clicking the title of an accordion then toggling the state, the state applies however doesn't take the current state into account. For example if the accordion is open ( by title click ) it will change the state to open when it should be changing it to closed.

There was also multiple events firing for Nathan as well, lets confirm that is not from our end.

## What I expected to happen

If the accordion is open the state should tell the accordion to close and vice versa.

## Reproducing

- Module name: accordion
- Module version: 5.0.2

Steps to reproduce:

1. Go to the [accordion react test page](https://uikit.service.gov.au/packages/accordion/tests/react/)
2. Click the title of the stateful accordion
3. Click the button `toggle state of accordion` once
4. The accordion will stay closed and not open

**Comment by sukhrajghuman** [comment]
@ndavison I've made a PR for this. Please see #546.

You can pass any of the following as props in the `<AUaccordion>`

`onOpen`: called when accordion is opening
`onClose`: called when accordion is closing
`afterOpen`: called when accordion has opened
`afterClose`: called when accordion has closed

example:

```jsx
<AUaccordion 
header="Accordion Heading" 
state={ this.state } 
onOpen={ () => { /** do something */ }} 
onClose={ () => { /** do something */ }} 
/>
```

**Comment by sukhrajghuman** [comment]
For more detail see here:

https://designsystem.gov.au/components/accordion/code/#props
