### ISSUE TITLE
React control inputs broken when one is selected

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/uikit#544]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Having the `checked` option on one or more control inputs is resulting in some strange behaviour. This only happens when using the react version of the snippet. 

```html
<AUradio label="Phone" name="radio-ex" />
<AUradio label="Tablet" name="radio-ex" checked />
<AUradio label="Laptop" name="radio-ex"  />
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20184809/47476919-58a4d600-d86e-11e8-802c-2bf9879f2c11.gif)

Behaviour is normal when all radio or checkbox are unchecked by default, i.e

```html
<AUradio label="Phone" name="radio-ex" />
<AUradio label="Tablet" name="radio-ex" />
<AUradio label="Laptop" name="radio-ex"  />
```

## Reproducing

- Module name: Control Inputs
- Module version: 2.16

**Comment by sukhrajghuman** [comment]
I'm guessing because once the prop 'checked` is given to the control input, there is not way of removing it. 

I believe you would have to manage the `checked` option using react state

**Comment by alex-page** [comment]
Nice find, lets jump on this next sprint!
