### ISSUE TITLE
Research other repository names for uikit

### ISSUE THREAD

**Issue by alex-page** [govau/uikit#585]

**Comment by adamzerella** [comment]
After a bit of digging this are the repository names for other government design systems:

- https://gov.uk
  - Name: **Gov.UK Design System**
  - Design System: `govuk-frontend`
  - Website: `govuk-design-system`

- https://usa.gov
  - Name: **United States Web Design System**
  - Design System: `uswds`
  - Website: `uswds-site`

- https://www.gov.sg/
  - Name: Singapore Design System
  - Design System: `?`
  - Website: `?`

**Comment by alex-page** [comment]
By unanimous decision:
```
govau/design-system-site
govau/design-system-components
```
