### ISSUE TITLE
Remove normalize.css from core

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#71]
# What's the problem with including it
The core currently depends on [normalize.css](https://github.com/necolas/normalize.css). That means the core has html output. With output each module we compile with `pancake syrup` will have the normalize.css included so we can't really use it as modules in eg react as that would duplicate and triple and quadruple the normalize.css output.
Also this is a dependency not in our control so it should be optional.

# What will removing mean
It means that the code we write has to be checked across each browsers and will come with side effects we can't all foresee.

# What's the next step
Remove normalize.css from core and retest all modules. Make sure by looking at the normalize.css code we build the ideas of it into our modules.

**Comment by klepas** [comment]
Is there anything we can document along the way with ``// comes from normalize` or something like that?

**Comment by dominikwilkowski** [comment]
it doesn't now
