### ISSUE TITLE
new module: dss-stages

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#96]
# uikit 1

<img width="731" alt="screen shot 2017-02-16 at 9 14 23 am" src="https://cloud.githubusercontent.com/assets/1266923/22997857/53b5993a-f428-11e6-8964-e680d39b68bb.png">

[Design guide](https://guides.service.gov.au/design-guide/components/badges/index.html)

**Comment by jonathanconway** [comment]
From experience, it would be good if these could be easily plugged into the [header](https://github.com/govau/uikit/issues/95).

**Comment by dominikwilkowski** [comment]
All modules are built in isolation so you can put them where ever you want :)

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/dss-stages
