### ISSUE TITLE
new modules: switch-input

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/uikit#97]
# design

- [ ] create design

# inspiration

<img width="392" alt="screen shot 2017-02-16 at 9 23 02 am" src="https://cloud.githubusercontent.com/assets/1266923/22998149/95ed90ae-f429-11e6-901d-f3d0d5c69d78.png">

https://gel.westpacgroup.com.au/GUI/STG/forms/#switches

**Comment by jonathanconway** [comment]
Nice.
Not sure if Westpac used this but here's another possible inspiration: https://github.com/russmaxdesign/switch-checkbox.

**Comment by dominikwilkowski** [comment]
Russ is great! :)

**Comment by dominikwilkowski** [comment]
Moved to: https://community.service.gov.au/t/switch-input
